const FIXED_TEXT=require('../fixtures/noise-fixed-texts.json');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {loaded,plain}=require('../helpers.cjs'),{documentStub,nodes}=require('../dom-stub.cjs');
const base={mainDate:'2026-09-10',mainTime:'15:00',mainZone:'3',mainMeasure:'no',a9Type:'business',a9Subject:'測試場所',a9Source:'抽水馬達'};
async function setup(){const e=await loaded();return {...e,gen:i=>e.root.DraftEngine.generate(e.config,'noise-main',i)};}
const noFinding=out=>{for(const s of Object.values(out))assert.equal((s.match(/於周界外巡查未發現有明顯噪音擾鄰情形/g)||[]).length,1);};
for(const [type,reason,phrase]of [['business','notOpen','稽查時現場未營業'],['factory','notWorking','稽查時現場未作業'],['construction','notBuilding','稽查時現場未施工'],['business','locked','現場大門深鎖'],['other','source','噪音源為抽水（加壓）馬達，現場未啟動'],['business','other','現場進行保養']])test('3.1.2單勾 '+reason+' 使用核定固定周界尾段',async()=>{const {gen}=await setup();const out=gen({...base,a9Type:type,a9Facility:'3',mainReasons:[reason],mainReasonOther:'現場進行保養'});noFinding(out);for(const s of Object.values(out))assert.ok(s.includes(phrase));});
test('3.1.2範例A、B逐字比對，舊notFound值不影響固定尾段',async()=>{const {gen}=await setup();for(const found of [false,true]){const out=gen({...base,mainReasons:found?['notOpen','notFound']:['notOpen']});assert.equal(out.record,'本局於115年9月10日15時許派員前往稽查，經查該址為測試場所，稽查時現場未營業'+("，" + FIXED_TEXT.patrol));assert.equal(out.reply,'有關臺端反映事項，'+out.record+(FIXED_TEXT.replyEnding));}});
test('3.1.2範例C、D逐字比對，設備案件固定尾段逐字一致',async()=>{const {gen}=await setup();for(const found of [false,true]){const out=gen({...base,mainReasons:found?['locked','source','notFound']:['locked','source']});assert.equal(out.record,'本局於115年9月10日15時許派員前往，經查為測試場所，現場大門深鎖，噪音源為抽水馬達，現場未啟動，'+'於周界外巡查未發現有明顯噪音擾鄰情形，'+'爾後將不定期派員巡查，以維當地環境品質。');assert.equal(out.reply,'有關臺端反映事項，'+out.record+(FIXED_TEXT.replyEnding));}});
test('3.1.2設備案件忽略舊未發現選值，未勾鎖門不得出現',async()=>{const {gen}=await setup();const out=gen({...base,mainReasons:['source','notFound']});for(const s of Object.values(out)){assert.match(s,/現場未啟動，於周界外巡查未發現有明顯噪音擾鄰情形/);assert.doesNotMatch(s,/大門深鎖|未營業/);}});
test('3.1.2原因事實固定排序且忽略舊選值，不依點選順序',async()=>{const {gen}=await setup();const reasons=['other','notFound','source','notOpen','locked'],i={...base,mainReasons:reasons,mainReasonOther:'現場進行保養。'};const out=gen(i);for(const s of Object.values(out)){assert.match(s,/現場大門深鎖，稽查時現場未營業，噪音源為抽水馬達，現場未啟動，現場進行保養，於周界外巡查未發現有明顯噪音擾鄰情形，爾後/);assert.doesNotMatch(s,/，，|。。|，。|。，|\s{2}/);}assert.deepEqual(plain(out),plain(gen({...i,mainReasons:[...reasons].reverse()})));});
test('3.1.2未勾其他不輸出殘留自填，設備必填驗證維持',async()=>{const {gen}=await setup();const out=gen({...base,mainReasons:['notOpen'],mainReasonOther:'不能帶入的舊原因'});for(const s of Object.values(out))assert.doesNotMatch(s,/不能帶入/);assert.throws(()=>gen({...base,mainReasons:['source'],a9Source:''}),/請先填寫噪音源/);});
test('3.1.2所有合法原因組合：兩份文件均使用單一固定尾段',async()=>{const {gen,config}=await setup(),spec=config.templates.find(t=>t.id==='noise-main').unmeasured.reasons;for(const type of ['factory','entertainment','business','construction','speaker','other']){const ids=spec.filter(r=>!r.types||r.types.includes(type)).map(r=>r.id);for(let mask=1;mask<2**ids.length;mask++){const selected=ids.filter((_,idx)=>mask&(1<<idx)),out=gen({...base,a9Type:type,a9Facility:'3',mainReasons:selected,mainReasonOther:'自訂現場事實'});for(const s of Object.values(out)){assert.equal(s.includes('未發現'),true,type+':'+selected.join(','));assert.equal(s.includes('大門深鎖'),selected.includes('locked'));assert.equal(s.includes('現場未啟動'),selected.includes('source'));assert.doesNotMatch(s,/尚待確認|，，|。。|，。|。，/);}}}});
test('3.1.2取消及重勾鎖門：清空舊草稿，重新產稿同步移除及恢復',async()=>{const e=await setup(),doc=documentStub(),app=doc.createElement('main');doc.getElementById=()=>app;e.context.document=doc;e.root.confirm=()=>true;e.root.TemplateLoader.load=async()=>e.config;e.run('src/field-renderer.js');e.run('src/sentence-app.js');await new Promise(r=>setImmediate(r));const button=t=>nodes(app).find(n=>n.tagName==='BUTTON'&&n.textContent===t),get=id=>nodes(app).find(n=>n.id===id),box=id=>nodes(app).find(n=>n.type==='checkbox'&&n.value===id),fill=(id,value)=>{get(id).value=value;get(id).dispatch('change');};button('噪音').dispatch('click');button('噪音案件').dispatch('click');for(const id of ['mainDate','mainTime','mainZone','mainMeasure','a9Type'])fill(id,base[id]);for(const id of ['notOpen','locked']){box(id).checked=true;box(id).dispatch('change');}fill('a9Subject',base.a9Subject);button('填入兩份草稿').dispatch('click');assert.match(get('record').value,/未發現/);for(const checked of [false,true]){box('locked').checked=checked;box('locked').dispatch('change');assert.equal(get('record').value,'');assert.equal(get('reply').value,'');button('填入兩份草稿').dispatch('click');for(const id of ['record','reply'])assert.equal(get(id).value.includes('大門深鎖'),checked);}});
