const {test}=require('node:test'),assert=require('node:assert/strict');const {loaded,plain}=require('./helpers.cjs');const {documentStub,nodes}=require('./dom-stub.cjs');
const base={scenario:'article9',a9Type:'construction',a9Zone:'3',a9Date:'2026-03-05',a9Time:'10:00',a9Frequency:'full',a9Rain:'no',a9Home:'no',a9Value_leq:'70',a9Value_lmax:'90',a9WindSpeed:'5.0',a9Subject:'測試工地',a9Operation:'作業中',a9Source:'測試機具'};
async function setup(){const env=await loaded();return {...env,m:env.root.NoiseArticle9Measurement,generate:input=>env.root.DraftEngine.generate(env.config,'noise-case',input),t:env.config.templates.find(t=>t.id==='noise-case')};}
test('可聞第9條聲音直接進入固定2分鐘量測，不問持續間歇代表性',async()=>{const {m,root,t}=await setup();assert.equal(m.assess(base).canMeasure,true);assert.equal(root.NOISE_ARTICLE9_RULES.measurement.durationSeconds,120);assert.equal(m.assess({...base,intermittent:'yes'}).canMeasure,true);assert.ok(!t.fields.some(f=>/是否持續|是否間歇|是否具有代表性|量測秒數/.test(f.label)));});
test('移除可聞及完成確認，舊欄位不能阻擋現有量測',async()=>{const {m,t}=await setup();assert.ok(!t.fields.some(f=>['a9Audible','a9Completed','a9Frequency','a9Wind'].includes(f.id)));assert.equal(m.assess({...base,a9Audible:'no',a9Completed:'no'}).status,'compliant');});
test('天雨路濕停止數值流程，兩份制式文字正確',async()=>{const {m,generate}=await setup(),input={...base,a9Rain:'yes',a9WindSpeed:'5.1'};assert.equal(m.assess(input).canMeasure,false);assert.equal(m.assess(input).status,'rain');const out=generate(input);assert.equal(out.record,'本局於115年3月5日10時許派員前往稽查，經查該址為測試工地，稽查時作業中，惟現場適逢天雨路濕依法規定不宜量測噪音，已責成業者加強噪音防制措施、注意作業時段，並請降低音量，避免擾鄰。');assert.match(out.reply,/有關臺端反映事項，本局於115年3月5日10時許/);assert.match(out.reply,/無法量測具代表性之數據/);assert.doesNotMatch(out.record,/70分貝|超過/);});
test('一般音源只有Leq，營建工程才有Lmax，低頻獨立',async()=>{const {m}=await setup();assert.deepEqual(plain(m.assess({...base,a9Type:'business'}).items.map(i=>i.id)),['leq']);assert.deepEqual(plain(m.assess(base).items.map(i=>i.id)),['leq','lmax']);assert.deepEqual(plain(m.assess({...base,a9Frequency:'both',a9Value_leqLF:'40'}).items.map(i=>i.id)),['leq','lmax','leqLF']);});
test('各項均未超標及等於標準直接符合，不需背景',async()=>{const {m}=await setup();for(const values of [{a9Value_leq:'70',a9Value_lmax:'90'},{a9Value_leq:'72',a9Value_lmax:'100'}]){const s=m.assess({...base,...values});assert.equal(s.status,'compliant');assert.equal(s.needsBackground,false);}});
for(const [name,patch,ids]of [['Leq超標Lmax合格',{a9Value_leq:'75'},['leq']],['Leq合格Lmax超標',{a9Value_lmax:'101'},['lmax']],['低頻超標',{a9Frequency:'both',a9Value_leqLF:'47'},['leqLF']],['三項超標',{a9Value_leq:'75',a9Value_lmax:'101',a9Frequency:'both',a9Value_leqLF:'47'},['leq','lmax','leqLF']]])test(name+'均需背景且只修正原超標項目',async()=>{const {m}=await setup();const s=m.assess({...base,...patch});assert.equal(s.needsBackground,true);assert.equal(s.ready,false);assert.deepEqual(plain(s.items.filter(i=>i.raw>i.standard).map(i=>i.id)),ids);const p=m.prepare({...base,...patch});for(const id of ['leq','lmax','leqLF'])assert.equal(p['a9ShowBg_'+id],ids.includes(id)?'yes':'no');});
test('D>=10不修正且公文不輸出實際差值',async()=>{const {m,generate}=await setup();assert.deepEqual(plain(m.correct(74.8,40.4)),{usable:true,value:74.8,corrected:false,difference:34.4});const out=generate({...base,a9Value_leq:'74.8',a9Bg_leq:'40.4'});assert.match(out.record,/均能與背景音量相差10分貝，依法不需修正/);assert.doesNotMatch(out.record,/34.4/);});
test('3<=D<10依公式自動修正，原未超標項目保留',async()=>{const {m}=await setup();for(const d of [3,4,5,6,7,8,9,9.999]){const c=m.correct(75,75-d);const expected=10*Math.log10(10**7.5-10**((75-d)/10));assert.ok(Math.abs(c.value-expected)<1e-10);assert.equal(c.corrected,true);}const s=m.assess({...base,a9Value_leq:'75',a9Bg_leq:'71',a9Bg_lmax:'89'});assert.equal(s.items[1].final,90);assert.equal(s.items[1].background,undefined);});
test('D<3該筆停止，不得產生符合或超標公文',async()=>{const {m,generate}=await setup();for(const bg of ['73','75','80']){const input={...base,a9Value_leq:'75',a9Bg_leq:bg},s=m.assess(input);assert.equal(s.status,'difference');assert.equal(s.ready,false);assert.equal(s.retry,true);assert.doesNotMatch(generate(input).record,/符合|超過|已違反/);}});
test('無法配合必填原因，不修正原始值',async()=>{const {m,generate}=await setup();const input={...base,a9Value_leq:'75',a9Unavailable:['unavailable']};assert.equal(m.assess(input).ready,false);const ready={...input,a9CannotReason:'無法停機'};assert.equal(m.assess(ready).status,'exceeded');assert.equal(m.assess(ready).items[0].final,75);assert.match(generate(ready).record,/原因：無法停機/);});
test('修正後等於標準值視為符合，不以顯示四捨五入決定',async()=>{const {m}=await setup();const bg=69,l1=10*Math.log10(10**7.2+10**(bg/10));const s=m.assess({...base,a9Value_leq:String(l1),a9Bg_leq:String(bg)});assert.equal(s.status,'compliant');assert.equal(m.assess({...base,a9Value_leq:'72.0001',a9Unavailable:['unavailable'],a9CannotReason:'無法停機'}).status,'exceeded');});
test('修正後仍超標只限期改善，不直接告發',async()=>{const {m,generate}=await setup(),input={...base,a9Value_leq:'75',a9Bg_leq:'71'};assert.equal(m.assess(input).status,'exceeded');const out=generate(input);assert.match(out.record,/依法限期改善，經限期改善仍未符合噪音管制標準者將依法告發/);assert.doesNotMatch(out.record,/直接告發|依法告發並令/);assert.doesNotMatch(out.reply,/背景音量|修正後音量/);});
test('風速超限數值可記錄但不採用，重測清空所有測量及背景值',async()=>{const {m}=await setup();const input={...base,a9WindSpeed:'5.1',a9Bg_leq:'40'};const s=m.assess(input);assert.equal(s.canMeasure,true);assert.equal(s.status,'wind');assert.equal(s.ready,false);const next=m.restart(input);assert.equal(next.a9Value_leq,'');assert.equal(next.a9Bg_leq,'');assert.equal(next.a9Type,'construction');assert.equal(m.assess(next).status,'pending');});
test('公文排列全頻最大低頻；非營建Lmax與未量頻率不出現',async()=>{const {generate}=await setup();const out=generate({...base,a9Frequency:'both',a9Value_leqLF:'41.2'}).record;assert.ok(out.indexOf('一般均能音量為70')<out.indexOf('最大音量為90'));assert.ok(out.indexOf('最大音量為90')<out.indexOf('低頻均能音量為41.2'));assert.doesNotMatch(generate({...base,a9Type:'business',a9Value_leq:'60'}).record,/最大音量|低頻均能/);});
test('測點依陳情人要求選擇，民眾回覆使用對應用字',async()=>{const {generate}=await setup();const out=generate({...base,a9Home:'yes'});assert.match(out.record,/陳情人指定之生活居住場所/);assert.match(out.reply,/臺端指定之生活居住場所/);assert.match(generate(base).record,/周界1公尺外之適當處所/);});
test('工廠核備背景僅限24小時全年運轉且核備有效，全頻可用低頻不套用',async()=>{const {m}=await setup();const input={...base,a9Type:'factory',a9Frequency:'both',a9Value_leq:'70',a9Value_leqLF:'45',a9Unavailable:['unavailable'],a9CannotReason:'無法停機',a9AllYear:'yes',a9AnnualValid:'yes',a9Annual_leq:'60'};const s=m.assess(input);assert.equal(s.ready,true);assert.equal(s.items[0].backgroundMode,'annual');assert.equal(s.items[1].backgroundMode,'unavailable');assert.equal(s.items[1].final,45);assert.equal(m.assess({...input,a9AnnualValid:''}).ready,false);assert.equal(m.assess({...input,a9AllYear:'no'}).items[0].backgroundMode,'unavailable');});
test('缺值未完成風速未確認及無標準不可產生結論，不採用偽造計算欄位',async()=>{const {m,generate}=await setup();for(const patch of [{a9Value_leq:'',a9Value_lmax:''},{a9WindSpeed:''},{a9Home:''},{a9Type:'speaker',a9Value_leq:'',a9Value_leqLF:'40'}]){const input={...base,...patch,a9Blocked:'no',a9Record:'偽造符合'};assert.equal(m.assess(input).ready,false);assert.doesNotMatch(generate(input).record,/偽造符合|已違反/);}});

test('表單一般音源不顯示Lmax，天雨隱藏全部測量欄位，風速在量測中記錄',async()=>{
 const env=await setup();env.context.document=documentStub();env.run('src/field-renderer.js');const view=env.root.FieldRenderer.render(env.t,()=>{});const get=id=>nodes(view.element).find(n=>n.id===id);
 view.write({...base,a9Type:'business',a9Value_leq:'60'});assert.equal(get('a9Value_leq').parentElement.hidden,false);assert.equal(get('a9Value_lmax').parentElement.hidden,true);assert.equal(get('a9WindSpeed').parentElement.hidden,false);
 view.write({...base,a9Rain:'yes'});for(const id of ['a9Value_leq','a9Value_lmax','a9WindSpeed','a9Bg_leq'])assert.equal(get(id).parentElement.hidden,true,id);
 view.write({...base,a9Value_leq:'75'});assert.equal(get('a9Bg_leq').parentElement.hidden,false);assert.equal(get('a9Bg_lmax').parentElement.hidden,true);
 view.write({...base,a9Value_leq:'',a9Value_lmax:'',a9Value_leqLF:'40'});assert.equal(get('a9Value_leq').parentElement.hidden,false);assert.equal(get('a9Value_lmax').parentElement.hidden,false);assert.equal(get('a9Value_leqLF').parentElement.hidden,false);
});
test('實際頁面完成量測產生草稿、風速失效清空草稿、重測後可重新產生',async()=>{
 const env=await setup(),doc=documentStub(),app=doc.createElement('main');doc.getElementById=()=>app;env.context.document=doc;env.root.confirm=()=>true;env.root.TemplateLoader.load=async()=>env.config;
 env.run('src/field-renderer.js');/* Internal legacy UI regression fixture; not a production entry. */ env.config.caseTypes.find(t=>t.id==='noise-case').directTemplateId='noise-case';env.run('src/sentence-app.js');await new Promise(resolve=>setImmediate(resolve));
 const get=id=>nodes(app).find(n=>n.id===id),button=label=>nodes(app).find(n=>n.tagName==='BUTTON'&&n.textContent===label),fill=(id,value)=>{get(id).value=value;get(id).dispatch('change');};
 button('噪音').dispatch('click');button('噪音案件').dispatch('click');
 for(const id of ['scenario','a9Type','a9Zone','a9Date','a9Time','a9Subject','a9Operation','a9Source','a9Rain','a9Home','a9Value_leq','a9Value_lmax','a9WindSpeed'])fill(id,base[id]);
 assert.equal(button('填入兩份草稿').parentElement.hidden,false);button('填入兩份草稿').dispatch('click');assert.match(get('record').value,/未超過/);
 fill('a9WindSpeed','5.1');assert.equal(get('record').value,'');assert.equal(button(env.root.NOISE_TEXTS.ui.retryWind).hidden,false);
 button(env.root.NOISE_TEXTS.ui.retryWind).dispatch('click');assert.equal(get('a9Value_leq').value,'');assert.equal(get('a9Bg_leq').value,'');assert.equal(get('a9Type').value,'construction');
 fill('a9Value_leq','70');fill('a9Value_lmax','90');fill('a9WindSpeed','5.0');button('填入兩份草稿').dispatch('click');assert.match(get('record').value,/未超過/);
});
test('背景更動觸發判定與公文更新、切換上游不殘留量測資料',async()=>{
 const env=await setup();env.context.document=documentStub();env.run('src/field-renderer.js');const view=env.root.FieldRenderer.render(env.t,()=>{}),get=id=>nodes(view.element).find(n=>n.id===id);
 view.write({...base,a9Value_leq:'75',a9Bg_leq:'71'});assert.equal(view.write(view.read()).a9Blocked,'no');
 get('a9Bg_leq').value='74';get('a9Bg_leq').dispatch('change');assert.equal(view.write(view.read()).a9Blocked,'yes');
 get('a9Type').value='business';get('a9Type').dispatch('change');for(const id of ['a9Value_leq','a9Value_lmax','a9Bg_leq','a9WindSpeed'])assert.equal(view.read()[id],'',id);
});
test('2.5標準表及第8條完整規則與判斷器保持不變',async()=>{
 const fs=require('fs'),path=require('path'),crypto=require('crypto');const env=await setup();const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/version25-manifest.json'),'utf8').replace(/^\uFEFF/,''));
 for(const name of ['data/templates/restaurant-odor.js','data/templates/restaurant-odor-sampling-pending.js']){const item=manifest.find(m=>m.Path==='\\'+name.replaceAll('/','\\'));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',name))).digest('hex').toUpperCase(),item.Hash);}
 assert.deepEqual(plain(env.root.NOISE_ARTICLE9_RULES.tables),require('./fixtures/version25-standards.json'));
});

test('三項超標以三筆不同背景值計算，不共用全頻低頻數據',async()=>{const {m}=await setup();const s=m.assess({...base,a9Frequency:'both',a9Value_leq:'75',a9Value_lmax:'101',a9Value_leqLF:'47',a9Bg_leq:'71',a9Bg_lmax:'90',a9Bg_leqLF:'40'});assert.equal(s.ready,true);assert.deepEqual(plain(s.items.map(i=>i.background)),[71,90,40]);assert.ok(Math.abs(s.items[0].final-m.correct(75,71).value)<1e-12);assert.equal(s.items[1].final,101);assert.ok(Math.abs(s.items[2].final-m.correct(47,40).value)<1e-12);});
test('量測判斷與公文具確定性，不修改事實或規則',async()=>{const {m,generate,root}=await setup();const input={...base,a9Value_leq:'75',a9Bg_leq:'71'},saved=JSON.stringify(input),rules=JSON.stringify(root.NOISE_ARTICLE9_RULES),expected=plain(m.assess(input)),doc=plain(generate(input));for(let i=0;i<20;i++){assert.deepEqual(plain(m.assess(input)),expected);assert.deepEqual(plain(generate(input)),doc);}assert.equal(JSON.stringify(input),saved);assert.equal(JSON.stringify(root.NOISE_ARTICLE9_RULES),rules);});

test('2.7只輸入Leq只比較及輸出Leq，低頻Lmax空白不顯示',async()=>{const {m,generate}=await setup();const input={...base,a9Value_lmax:'',a9Value_leqLF:''};assert.deepEqual(plain(m.assess(input).items.map(i=>i.id)),['leq']);const out=generate(input);assert.match(out.record,/一般均能音量為70分貝/);assert.doesNotMatch(out.record,/最大音量|低頻均能/);assert.equal(m.assess({...input,a9Value_leq:''}).ready,false);});
test('2.7只有低頻或Lmax也可独立判斷，零不等於空白',async()=>{const {m,generate}=await setup();const low={...base,a9Value_leq:'',a9Value_lmax:'',a9Value_leqLF:'40'};assert.deepEqual(plain(m.assess(low).items.map(i=>i.id)),['leqLF']);assert.doesNotMatch(generate(low).record,/一般均能音量|最大音量/);assert.deepEqual(plain(m.assess({...low,a9Value_leqLF:'',a9Value_lmax:'90'}).items.map(i=>i.id)),['lmax']);assert.equal(m.assess({...low,a9Value_leqLF:'0'}).status,'compliant');});
test('2.7風速5可採用、5.1不採用、缺漏與舊選項不能替代',async()=>{const {m,generate}=await setup();assert.equal(m.assess({...base,a9WindSpeed:'5.0'}).status,'compliant');for(const a9WindSpeed of ['5.1','6']){const input={...base,a9WindSpeed};assert.equal(m.assess(input).status,'wind');assert.equal(m.assess(input).retry,true);assert.doesNotMatch(generate(input).record,/已違反|符合標準/);}for(const a9WindSpeed of ['','-1','abc'])assert.equal(m.assess({...base,a9WindSpeed,a9Wind:'no'}).ready,false);});
for(const [raw,bg,status] of [['73','69','compliant'],['75','71','exceeded']])test('2.7修正後'+status+'畫面顯示原值背景修正值標準及結果',async()=>{const env=await setup();env.context.document=documentStub();env.run('src/field-renderer.js');const view=env.root.FieldRenderer.render(env.t,()=>{});const input={...base,a9Value_leq:raw,a9Bg_leq:bg};view.write(input);const node=nodes(view.element).find(n=>n.id==='a9CorrectionDetails');assert.equal(node.tagName,'P');assert.equal(node.parentElement.hidden,false);for(const text of ['原始量測值：'+raw,'背景音量：'+bg,'音量修正後數值：','適用管制標準：72',status==='compliant'?'符合標準':'超過標準'])assert.ok(node.textContent.includes(text),text);assert.equal(env.m.assess(input).status,status);});
test('2.7原始超標修正後合格紀錄保留背景量測及修正數值',async()=>{const {generate}=await setup();const out=generate({...base,a9Value_leq:'73',a9Bg_leq:'69'});assert.match(out.record,/一般均能音量為73分貝/);assert.match(out.record,/另請業者關閉噪音源後量測背景音量為69分貝，經背景音量修正後，修正後一般均能音量為/);assert.match(out.record,/未超過/);assert.doesNotMatch(out.reply,/背景音量|第1項/);});
for(const [type,clause] of [['factory',1],['entertainment',2],['business',3],['construction',4],['speaker',5],['other',6]])test('2.7'+type+'超標帶第9條第1項第'+clause+'款',async()=>{const {generate,m,root}=await setup();for(const facility of type==='other'?root.NOISE_ARTICLE9_RULES.facilities.map(f=>f.id):['']){const input={...base,a9Type:type,a9Facility:facility,a9Value_leq:'120',a9Value_lmax:'',a9Bg_leq:'40'};assert.equal(m.assess(input).status,'exceeded');const out=generate(input);assert.match(out.record,new RegExp('已違反噪音管制法第9條第1項第'+clause+'款規定'));assert.doesNotMatch(out.reply,/第1項/);assert.match(out.reply,/依法限期改善/);}});
test('2.7所有量測欄位依標準可用性顯示，無三項已刪除欄位',async()=>{const env=await setup();env.context.document=documentStub();env.run('src/field-renderer.js');const view=env.root.FieldRenderer.render(env.t,()=>{}),get=id=>nodes(view.element).find(n=>n.id===id);for(const id of ['a9Frequency','a9Completed','a9Audible','a9Wind'])assert.equal(get(id),undefined);view.write({...base,a9Value_leq:'',a9Value_lmax:''});for(const id of ['a9Value_leq','a9Value_lmax','a9Value_leqLF'])assert.equal(get(id).parentElement.hidden,false);view.write({...base,a9Type:'business'});assert.equal(get('a9Value_lmax').parentElement.hidden,true);assert.equal(get('a9Value_leqLF').parentElement.hidden,false);view.write({...base,a9Type:'speaker'});assert.equal(get('a9Value_leqLF').parentElement.hidden,true);assert.equal(get('a9WindSpeed').type,'number');});

test('2.7背景修正公式及機器精度比較保留2.6原程式',()=>{const fs=require('fs'),path=require('path'),previous=require('./fixtures/version26-calculation.json');const current=fs.readFileSync(path.join(__dirname,'../src/noise-article9-measurement.js'),'utf8');assert.equal(current.slice(current.indexOf(' function correct('),current.indexOf(' function assess(')),previous.correct);assert.equal(current.slice(current.indexOf('  // Normalize only'),current.indexOf('\n }\n const keys=')),previous.precision);});
