const {test}=require('node:test'),assert=require('node:assert/strict');const {loaded,plain}=require('./helpers.cjs');const {documentStub,nodes}=require('./dom-stub.cjs');
const base={scenario:'article9',a9Type:'construction',a9Zone:'3',a9Date:'2026-03-05',a9Time:'10:00',a9Rain:'no',a9Home:'no',a9Value_leq:'75',a9WindSpeed:'5.0',a9Bg_leq:'72.1',a9Subject:'測試場所',a9Operation:'作業中',a9Source:'測試音源'};
async function setup(){const env=await loaded();return {...env,m:env.root.NoiseArticle9Measurement,generate:input=>env.root.DraftEngine.generate(env.config,'noise-case',input)};}
for(const [d,usable,corrected]of [[2.9,false,false],[3,true,true],[9.9,true,true],[10,true,false]])test('差值'+d+'嚴格套用原修正門檻',async()=>{const {m}=await setup(),c=m.correct(75,75-d);assert.equal(c.usable,usable);if(usable)assert.equal(c.corrected,corrected);const s=m.assess({...base,a9Bg_leq:String(75-d)});assert.equal(s.retry,!usable);});
for(const kind of ['wind','difference']){
 test(kind+'可重測清空數據及背景，保留案件資料',async()=>{const {m}=await setup();const input={...base,a9WindSpeed:kind==='wind'?'5.1':'5.0'},s=m.assess(input);assert.equal(s.status,kind);assert.equal(s.retry,true);const next=m.restart(input);for(const key of ['a9Value_leq','a9Bg_leq','a9WindSpeed','a9Exit'])assert.equal(next[key],'');assert.equal(next.a9Subject,base.a9Subject);assert.equal(m.assess(next).ready,false);});
 test(kind+'結束產生指定兩份公文，不作合格超標或第9條違規認定',async()=>{const {m,generate,root}=await setup();const ended=m.finish({...base,a9WindSpeed:kind==='wind'?'5.1':'5.0'}),s=m.assess(ended);assert.equal(s.status,kind+'Ended');assert.equal(s.ready,true);assert.equal(s.retry,false);if(kind==='wind')assert.equal(s.needsBackground,false);const out=generate(ended);for(const text of Object.values(out)){assert.doesNotMatch(text,/已違反|依法告發|判定符合|量測符合/);assert.ok(text.includes(kind==='wind'?'量測期間風速大於5公尺/秒':(text===out.record?'差值小於3分貝':'相差小於3分貝')));}const values={date:'115年3月5日',time:'10時許',subject:'測試場所',operation:'作業中',noiseSource:'測試音源'};for(const key of (kind==='wind'?['record','reply']:['reply']))assert.equal(out[key],root.NOISE_ARTICLE9_DOCUMENTS[kind+'Ended'][key].replace(/\{\{(\w+)\}\}/g,(_,k)=>values[k]));assert.match(out.reply,/若您再次發現污染情形/);});
 test(kind+'頁面提供兩個出口，結束後可產生及複製正常草稿',async()=>{const env=await setup(),doc=documentStub(),app=doc.createElement('main');doc.getElementById=()=>app;env.context.document=doc;env.root.confirm=()=>true;env.root.TemplateLoader.load=async()=>env.config;env.run('src/field-renderer.js');/* Internal legacy UI regression fixture; not a production entry. */ env.config.caseTypes.find(t=>t.id==='noise-case').directTemplateId='noise-case';env.run('src/sentence-app.js');await new Promise(r=>setImmediate(r));const btn=t=>nodes(app).find(n=>n.tagName==='BUTTON'&&n.textContent===t),get=id=>nodes(app).find(n=>n.id===id),fill=(id,value)=>{get(id).value=value;get(id).dispatch('change');};btn('噪音').dispatch('click');btn('噪音案件').dispatch('click');const input={...base,a9WindSpeed:kind==='wind'?'5.1':'5.0'};for(const id of ['scenario','a9Type','a9Zone','a9Date','a9Time','a9Subject','a9Operation','a9Source','a9Rain','a9Home','a9Value_leq','a9WindSpeed',...(kind==='difference'?['a9Bg_leq']:[])])fill(id,input[id]);const labels=env.root.NOISE_ARTICLE9_DOCUMENTS.exitActions[kind];assert.equal(btn(labels.retry).hidden,false);assert.equal(btn(labels.finish).hidden,false);btn(labels.finish).dispatch('click');assert.equal(btn('填入兩份草稿').parentElement.hidden,false);btn('填入兩份草稿').dispatch('click');assert.match(get('record').value,/無法(?:取得可)?作為執法依據/);assert.ok(nodes(app).filter(n=>n.tagName==='BUTTON'&&n.textContent==='複製文字').length===2);});
}
test('5.0可用且不能偽造不符條件的結束原因，編輯量測清除舊出口',async()=>{const {m}=await setup();assert.equal(m.assess({...base,a9Value_leq:'70',a9Exit:'wind'}).status,'compliant');assert.equal(m.assess({...base,a9Exit:'wind'}).status,'difference');const ended=m.finish({...base,a9WindSpeed:'5.1'});const env=await loaded();assert.equal(env.root.TemplateWorkflows.noiseArticle8.resetChange(ended,{...ended,a9WindSpeed:'5.0'}).a9Exit,'');});
