const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {loaded,plain}=require('./helpers.cjs'),{documentStub,nodes}=require('./dom-stub.cjs');
const base={mainDate:'2026-09-11',mainTime:'10:00',mainZone:'3',mainAct:'none',mainMeasure:'yes',a9Type:'business',a9Subject:'88',a9Source:'77',a9Rain:'no',a9Home:'no',a9Value_leq:'80',a9WindSpeed:'1.4'};
async function setup(){const e=await loaded(),t=e.config.templates.find(t=>t.id==='noise-main');e.context.document=documentStub();e.run('src/field-renderer.js');const norm=i=>e.root.DraftEngine.normalize(t,i),w=e.root.TemplateWorkflows.noiseMain,view=e.root.FieldRenderer.render(t,()=>{});return {...e,t,w,view,norm,get:id=>nodes(view.element).find(n=>n.id===id),gen:i=>e.root.DraftEngine.generate(e.config,t.id,i),series:values=>{let n=base;values.forEach((value,index)=>{if(index)n=norm(w.restart(n));n=norm({...n,a9Bg_leq:String(value)});});return norm(w.finish(n));}};}
for(const values of [[79],[79,78],[79,78,79],[79,78,79,78.5],[79,78,79,78.5,79.5]])test('3.7.1結束稽查紀錄動態列'+values.length+'筆背景',async()=>{const {series,gen}=await setup();const d=gen(series(values));for(const [index,value]of values.entries())assert.ok(d.record.includes(values.length===1?'另量測背景音量為'+value+'分貝':'第'+(index+1)+'次為'+value+'分貝'));assert.match(d.record,values.length===1?/其與整體音量之差值小於3分貝/:/其與整體音量之差值均小於3分貝/);assert.doesNotMatch(d.record,/差值為|差1分貝|差2分貝|第0次|undefined|\{\{/);});
test('3.7.1完整核定範例與句號',async()=>{const {series,gen}=await setup();assert.equal(gen(series([79,78,79])).record,'本局於115年9月11日10時許派員前往稽查，經查該址為88，稽查時現場作業中，噪音源為77，經量測均能音量為80分貝，另量測背景音量，第1次為79分貝、第2次為78分貝、第3次為79分貝，其與整體音量之差值均小於3分貝，依噪音管制標準規定無法取得可作為執法依據之量測值。現場已責成業者加強噪音防制措施、注意作業時段，並請降低音量，避免擾鄰。');});
test('3.7.1每種背景筆數結案均有正確標點',async()=>{const {series,gen}=await setup();for(const values of [[79],[79,78],[79,78,79,78]]){const d=gen(series(values));assert.match(d.record,/量測值。現場已責成/);assert.doesNotMatch(d.record,/量測值現場|，，|。。/);}});
test('3.7.1民眾回覆不列背景歷程且保持1999',async()=>{const {series,gen,root}=await setup();const d=gen(series([79,78,79]));assert.doesNotMatch(d.reply,/第1次|第2次|第3次|79|78/);assert.match(d.reply,/兩者相差小於3分貝/);assert.ok(d.reply.endsWith(root.NOISE_TEXTS.common.replyEnding));});
test('3.7.1背景79、78後76有效，只用80與76',async()=>{const {series,norm,w,gen,root}=await setup();let n=series([79,78]);n=norm(w.restart(n));n=norm({...n,a9Bg_leq:'76'});const d=gen(n),rows=root.NoiseBackgrounds.list(n.backgroundMeasurements);assert.equal(rows.length,3);assert.equal(rows[2].selected,true);assert.match(d.record,/80分貝/);assert.match(d.record,/背景音量為76分貝/);assert.doesNotMatch(d.record,/79分貝|78分貝|第1次|第2次/);assert.equal(root.NoiseArticle9Measurement.assess(root.NoiseMain.article9(n)).items[0].correction.difference,4);});
test('3.7.1時間只有雙select，無自由輸入框',async()=>{const {get}=await setup();assert.equal(get('mainTime').tagName,'DIV');assert.equal(get('mainTimeHour').tagName,'SELECT');assert.equal(get('mainTimeMinute').tagName,'SELECT');});
test('3.7.1小時完整00至23',async()=>{const {get}=await setup();assert.deepEqual(get('mainTimeHour').options.filter(o=>o.value!=='').map(o=>o.value),Array.from({length:24},(_,i)=>String(i).padStart(2,'0')));});
test('3.7.1分鐘完整00至59',async()=>{const {get}=await setup();assert.deepEqual(get('mainTimeMinute').options.filter(o=>o.value!=='').map(o=>o.value),Array.from({length:60},(_,i)=>String(i).padStart(2,'0')));});
test('3.7.1時間初始未選且不依locale顯示AM/PM',async()=>{const {view,get}=await setup();assert.equal(view.read().mainTime,'');assert.equal(get('mainTimeHour').value,'');assert.equal(get('mainTimeMinute').value,'');assert.doesNotMatch(get('mainTime').textContent,/AM|PM|上午|下午/);});
test('3.7.1只選小時時不假定分鐘00，完成分鐘後才組合',async()=>{const {view,get}=await setup();get('mainTimeHour').value='23';get('mainTimeHour').dispatch('change');assert.equal(view.read().mainTime,'');assert.equal(get('mainTimeHour').value,'23');get('mainTimeMinute').value='40';get('mainTimeMinute').dispatch('change');assert.equal(view.read().mainTime,'23:40');});
test('3.7.1也支援先選分鐘再選小時',async()=>{const {view,get}=await setup();get('mainTimeMinute').value='05';get('mainTimeMinute').dispatch('change');assert.equal(view.read().mainTime,'');get('mainTimeHour').value='08';get('mainTimeHour').dispatch('change');assert.equal(view.read().mainTime,'08:05');});
for(const time of ['23:40','00:40','08:05'])test('3.7.1選擇'+time+'內部保留分鐘，兩份公文僅幾時許',async()=>{const {view,get,gen}=await setup();view.write({...base,a9Value_leq:'20'});get('mainTimeHour').value=time.slice(0,2);get('mainTimeHour').dispatch('change');get('mainTimeMinute').value=time.slice(3);get('mainTimeMinute').dispatch('change');assert.equal(view.read().mainTime,time);for(const text of Object.values(gen(view.read()))){assert.ok(text.includes(Number(time.slice(0,2))+'時許'));assert.doesNotMatch(text,/時\d+分許/);}});
test('3.7.1選23:40仍可篩出第8條營建行為',async()=>{const {view,get,root}=await setup();view.write(base);get('mainTimeHour').value='23';get('mainTimeHour').dispatch('change');get('mainTimeMinute').value='40';get('mainTimeMinute').dispatch('change');assert.ok(root.NoiseMain.route(view.read()).state.candidates.some(a=>a.id==='construction'));});
test('3.7.1第3類23:40判夜間且套既有標準',async()=>{const {root}=await setup();const s=root.NoiseArticle9Measurement.assess(root.NoiseMain.article9({...base,mainTime:'23:40'}));assert.equal(s.lookup.period,'night');assert.equal(s.items[0].standard,52);});
test('3.7.1時間分鐘不丟失22:59與23:00時段差異',async()=>{const {view,get,root}=await setup();view.write({...base,mainTime:'22:59'});assert.equal(root.NoiseArticle9Measurement.assess(root.NoiseMain.article9(view.read())).lookup.period,'evening');get('mainTimeHour').value='23';get('mainTimeHour').dispatch('change');get('mainTimeMinute').value='00';get('mainTimeMinute').dispatch('change');assert.equal(view.read().mainTime,'23:00');assert.equal(root.NoiseArticle9Measurement.assess(root.NoiseMain.article9(view.read())).lookup.period,'night');});
test('3.7.1只修改分鐘智慧保留場所音源量測及背景',async()=>{const {view,get}=await setup();view.write({...base,a9Bg_leq:'70'});get('mainTimeMinute').value='40';get('mainTimeMinute').dispatch('change');for(const key of ['a9Subject','a9Source','a9Value_leq','a9WindSpeed'])assert.equal(view.read()[key],base[key]);assert.equal(view.read().a9Bg_leq,'70');});
async function appSetup(){const e=await setup(),doc=documentStub(),app=doc.createElement('main');doc.getElementById=()=>app;e.context.document=doc;e.root.confirm=()=>true;e.root.TemplateLoader.load=async()=>e.config;e.run('src/sentence-app.js');await new Promise(r=>setImmediate(r));const get=id=>nodes(app).find(n=>n.id===id),button=t=>nodes(app).find(n=>n.tagName==='BUTTON'&&n.textContent===t),fill=(id,value)=>{get(id).value=value;get(id).dispatch('change');};button('噪音').dispatch('click');button('噪音案件').dispatch('click');fill('mainDate',base.mainDate);fill('mainTimeHour','10');fill('mainTimeMinute','00');for(const [key,value]of Object.entries(base))if(!['mainDate','mainTime'].includes(key))fill(key,value);return {...e,get,button,fill};}
test('3.7.1頁面改分鐘清除草稿但保留有效量測',async()=>{const {get,button,fill}=await appSetup();fill('a9Value_leq','20');button('填入兩份草稿').dispatch('click');assert.ok(get('record').value);fill('mainTimeMinute','40');assert.equal(get('record').value,'');assert.equal(get('reply').value,'');assert.equal(get('a9Value_leq').value,'20');assert.equal(get('a9Subject').value,'88');});
test('3.7.1頁面D<3背景重測仍鎖原80並列三次背景',async()=>{const {get,button,fill}=await appSetup();for(const [i,value]of ['79','78','79'].entries()){if(i)button('再次量測背景音量').dispatch('click');fill('a9Bg_leq',value);}assert.equal(get('a9Value_leq').value,'80');button('結束本次量測').dispatch('click');button('填入兩份草稿').dispatch('click');assert.match(get('record').value,/第1次為79分貝、第2次為78分貝、第3次為79分貝/);assert.doesNotMatch(get('reply').value,/第1次/);});
test('3.7.1時間修改不修改風速小數字串',async()=>{const {view,get}=await setup();view.write({...base,a9WindSpeed:'1.40'});get('mainTimeMinute').value='59';get('mainTimeMinute').dispatch('change');assert.equal(view.read().a9WindSpeed,'1.40');});
for(const bg of ['77','70'])test('3.7.1D邊界背景'+bg+'不列無效歷次模板',async()=>{const {gen,norm,root}=await setup();const n=norm({...base,a9Bg_leq:bg});assert.equal(n.a9Retry,'no');assert.doesNotMatch(gen(n).record,/第1次|無法取得可作為執法依據/);const c=root.NoiseArticle9Measurement.assess(root.NoiseMain.article9(n)).items[0].correction;assert.equal(c.corrected,bg==='77');});
test('3.7.1原規則公式、背景與完整attempt模組未修改',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/version36-manifest.json'),'utf8').replace(/^\uFEFF/,''));for(const file of ['data/rules/noise-article8.js','data/rules/noise-article9.js','src/noise-article8.js','src/noise-article9.js','src/noise-article9-measurement.js','src/noise-backgrounds.js','src/noise-attempts.js','data/texts/noise-neighbor.js','data/templates/restaurant-odor.js','data/templates/restaurant-odor-sampling-pending.js']){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',file))).digest('hex').toUpperCase(),manifest.find(x=>x.Path==='\\'+file.replaceAll('/','\\')).Hash,file);}});
test('3.7.1本機版本metadata及集中文字',async()=>{const {root,config}=await setup();for(const t of config.templates.filter(t=>t.categoryId==='noise'))assert.equal(t.version,'3.7.1');assert.equal(root.NOISE_TEXTS.ui.endedBackground.conclusion.endsWith('。'),true);assert.deepEqual(plain(root.NOISE_TEXTS.ui.timePicker),{hour:'時',minute:'分',empty:'—'});});
test('3.7.1多項音量分別列背景，不混成同一音量',async()=>{const {norm,w,gen}=await setup();let n=norm({...base,a9Value_leqLF:'50',a9Bg_leq:'79',a9Bg_leqLF:'49'});n=norm(w.restart(n));n=norm({...n,a9Bg_leq:'78',a9Bg_leqLF:'48'});const d=gen(norm(w.finish(n)));assert.match(d.record,/均能音量為80分貝，另量測背景音量，第1次為79分貝、第2次為78分貝/);assert.match(d.record,/低頻均能音量為50分貝，另量測背景音量，第1次為49分貝、第2次為48分貝/);assert.doesNotMatch(d.reply,/第1次|49分貝/);});
test('3.7.1清空分鐘不補00，重選仍沿用原小時',async()=>{const {view,get}=await setup();view.write({...base,mainTime:'23:40'});get('mainTimeMinute').value='';get('mainTimeMinute').dispatch('change');assert.equal(view.read().mainTime,'');assert.equal(get('mainTimeHour').value,'23');get('mainTimeMinute').value='00';get('mainTimeMinute').dispatch('change');assert.equal(view.read().mainTime,'23:00');});
