const {test}=require('node:test'),assert=require('node:assert/strict');const {loaded}=require('./helpers.cjs');const {documentStub,nodes}=require('./dom-stub.cjs');
const base={scenario:'article9',a9Type:'construction',a9Zone:'3',a9Date:'2026-03-05',a9Time:'10:00',a9Rain:'no',a9Home:'no',a9Value_leq:'75',a9WindSpeed:'5.0',a9Subject:'測試場所',a9Operation:'作業中',a9Source:'測試音源'};
async function setup(){const env=await loaded();env.context.document=documentStub();env.run('src/field-renderer.js');const t=env.config.templates.find(t=>t.id==='noise-case'),view=env.root.FieldRenderer.render(t,()=>{});return {...env,t,view,m:env.root.NoiseArticle9Measurement,get:id=>nodes(view.element).find(n=>n.id===id),box:()=>nodes(view.element).find(n=>n.type==='checkbox'&&n.value==='unavailable')};}
test('2.9超標直接顯示背景數值，沒有關閉音源確認題',async()=>{const {view,get,t,m}=await setup();view.write(base);assert.equal(get('a9CanStop'),undefined);assert.ok(!t.fields.some(f=>/是否能配合關閉/.test(f.label)));assert.equal(get('a9Bg_leq').parentElement.hidden,false);assert.equal(get('a9CannotReason').parentElement.hidden,true);assert.equal(m.assess({...base,a9Bg_leq:'71'}).ready,true);});
test('2.9例外為主動勾選，清除背景數值且原因必填；取消恢復輸入',async()=>{const {view,get,box,m}=await setup();view.write({...base,a9Bg_leq:'71'});assert.equal(box().checked,false);box().checked=true;box().dispatch('change');assert.equal(view.read().a9Bg_leq,'');assert.equal(get('a9Bg_leq').parentElement.hidden,true);assert.equal(get('a9CannotReason').parentElement.hidden,false);assert.equal(m.assess(view.read()).ready,false);get('a9CannotReason').value='現場無法停機';get('a9CannotReason').dispatch('change');assert.equal(m.assess(view.read()).status,'exceeded');assert.equal(m.assess(view.read()).items[0].final,75);box().checked=false;box().dispatch('change');assert.equal(get('a9Bg_leq').parentElement.hidden,false);assert.equal(view.read().a9CannotReason,'');assert.equal(m.assess(view.read()).ready,false);});
test('2.9混入背景與例外資料時不會同時生效，公文註明原因',async()=>{const {view,root,config,m}=await setup();const input=view.write({...base,a9Unavailable:['unavailable'],a9CannotReason:'無法停機',a9Bg_leq:'74'});assert.equal(input.a9Bg_leq,'');assert.equal(m.assess(input).items[0].backgroundMode,'unavailable');const out=root.DraftEngine.generate(config,'noise-case',input);assert.match(out.record,/無法取得背景音量（原因：無法停機），不修正背景音量/);assert.doesNotMatch(out.record,/背景音量為74/);});
test('2.9上游條件變更清除背景例外原因，包含風速重新計算',async()=>{const {root}=await setup();const prior={...base,a9Bg_leq:'71',a9Unavailable:['unavailable'],a9CannotReason:'舊原因',a9Annual_leq:'60'};for(const change of [{a9Type:'business'},{a9Zone:'2'},{a9Time:'22:00'},{a9Value_leq:'76'},{a9WindSpeed:'4.9'}]){const next=root.TemplateWorkflows.noiseArticle8.resetChange(prior,{...prior,...change});assert.ok(!next.a9Unavailable?.length);assert.equal(next.a9Bg_leq,'');assert.equal(next.a9CannotReason,'');assert.equal(next.a9Annual_leq,'');}});
test('2.9工廠仍可使用核備背景，正常輸入無須回答工廠特例',async()=>{const {m,view,get}=await setup();view.write({...base,a9Type:'factory'});assert.equal(get('a9AllYear').parentElement.hidden,true);const s=m.assess({...base,a9Type:'factory',a9Unavailable:['unavailable'],a9CannotReason:'無法停機',a9AllYear:'yes',a9AnnualValid:'yes',a9Annual_leq:'60'});assert.equal(s.items[0].backgroundMode,'annual');assert.equal(s.ready,true);});
for(const [kind,patch,phrase]of [['wind',{a9WindSpeed:'5.1'},'量測期間風速大於5公尺/秒，依噪音管制標準規定該噪音值無法作為執法依據'],['difference',{a9Bg_leq:'72.1'},'兩者相差小於3分貝，依噪音管制標準規定該噪音值無法作為執法依據']])test('2.9'+kind+'兩份結束公文使用核定執法依據文字',async()=>{const {m,root,config}=await setup();const input=m.finish({...base,...patch});const s=m.assess(input);assert.equal(s.status,kind+'Ended');const out=root.DraftEngine.generate(config,'noise-case',input);for(const text of Object.values(out)){assert.ok(text.includes(kind==='difference'&&text===out.record?'其與整體音量之差值小於3分貝':phrase));assert.doesNotMatch(text,/已違反|符合噪音管制標準|超過噪音管制標準|無法取得可採用之/);}});
