const {test}=require('node:test'),assert=require('node:assert/strict');
const {loaded,plain}=require('./helpers.cjs'),{documentStub,nodes}=require('./dom-stub.cjs');
async function setup(id='noise-main'){const e=await loaded();e.context.document=documentStub();e.run('src/field-renderer.js');const t=e.config.templates.find(t=>t.id===id),view=e.root.FieldRenderer.render(t,()=>{});return {...e,t,view,get:id=>nodes(view.element).find(n=>n.id===id)};}
const base={mainDate:'2026-09-10',mainTime:'23:00',mainZone:'3',mainAct:'none',mainMeasure:'yes',a9Type:'business',a9Subject:'測試場所',a9Source:'測試設備',a9Rain:'no',a9Home:'no'};
test('3.2噪音主流程與近鄰無select或傳統radio，時間依3.7.1採雙select例外',async()=>{for(const id of ['noise-main','noise-neighbor']){const {view}=await setup(id);assert.equal(nodes(view.element).filter(n=>(n.tagName==='SELECT'&&!['mainTimeHour','mainTimeMinute'].includes(n.id))||n.type==='radio').length,0);assert.ok(nodes(view.element).some(n=>n.role==='radiogroup'));}});
for(const [id,patch,count]of [['mainZone',{},4],['a9Type',{},6],['a9Facility',{a9Type:'other'},8],['mainMeasure',{},2],['a9Rain',{},2],['a9Home',{},2]])test('3.2 '+id+' 直接展開所有適用單選卡',async()=>{const {view,get}=await setup();view.write({...base,...patch});const group=get(id);assert.equal(group.role,'radiogroup');assert.equal(group.parentElement.hidden,false);assert.equal(group.options.filter(o=>o.value&&!o.hidden).length,count);assert.ok(group.options.every(o=>o.tagName==='BUTTON'&&o.type==='button'&&o.role==='radio'));});
test('3.2單選點擊會取消原值並顯示aria選中狀態',async()=>{const {view,get}=await setup();view.write(base);const group=get('mainZone');group.options.find(o=>o.value==='2').dispatch('click');assert.equal(view.read().mainZone,'2');assert.equal(group.options.find(o=>o.value==='2')['aria-checked'],'true');assert.equal(group.options.find(o=>o.value==='3')['aria-checked'],'false');assert.equal(group.options.filter(o=>o['aria-checked']==='true').length,1);});
test('3.2方向鍵、Home、End與停用選項遵循單選語意',async()=>{const {root,context}=await setup();let value;const c=root.ChoiceControls.single({id:'unit',label:'測試',options:[{id:'a',label:'A'},{id:'b',label:'B',disabled:true},{id:'c',label:'C'}],onChange:()=>{value=c.element.value;}});context.document.createElement('div').append(c.element);const [a,b,cButton]=c.element.options;c.element.value='a';b.dispatch('click');assert.equal(c.element.value,'a');let prevented=false;a.dispatch('keydown',{key:'ArrowRight',preventDefault(){prevented=true;}});assert.equal(value,'c');assert.equal(cButton.focused,true);assert.equal(prevented,true);cButton.dispatch('keydown',{key:'Home',preventDefault(){}});assert.equal(value,'a');a.dispatch('keydown',{key:'End',preventDefault(){}});assert.equal(value,'c');assert.equal(c.element.options.filter(o=>o.tabIndex===0).length,1);});
test('3.2條件式候選只顯示引擎允許值，改區域清除舊值',async()=>{const {root,view,get}=await setup();const input={...base,mainZone:'1',mainAct:'commercialMachinery'};view.write(input);assert.deepEqual(plain(get('mainAct').options.filter(o=>o.value&&!o.hidden).map(o=>o.value)),[...root.NoiseMain.route(input).state.candidates.map(a=>a.id),'none']);get('mainZone').options.find(o=>o.value==='4').dispatch('click');assert.equal(view.read().mainAct,'');assert.equal(get('mainAct').options.find(o=>o.value==='commercialMachinery').hidden,true);});
test('3.2未量測與背景例外仍為原生checkbox，可多選及取消',async()=>{const {view}=await setup();view.write({...base,mainMeasure:'no'});const box=id=>nodes(view.element).find(n=>n.type==='checkbox'&&n.value===id);for(const id of ['locked','notOpen']){box(id).checked=true;box(id).dispatch('change');}assert.deepEqual(plain(view.read().mainReasons),['locked','notOpen']);box('locked').checked=false;box('locked').dispatch('change');assert.deepEqual(plain(view.read().mainReasons),['notOpen']);assert.ok(box('unavailable'));});
test('3.2近鄰自訂卡仍展開自填，輸出採原分流',async()=>{const {view,get,root,config}=await setup('noise-neighbor');get('noiseType').options.find(o=>o.value==='custom').dispatch('click');assert.equal(get('noiseTypeCustom').parentElement.hidden,false);get('noiseTypeCustom').value='測試生活聲響';get('noiseTypeCustom').dispatch('change');get('hasCommittee').options.find(o=>o.value==='yes').dispatch('click');const out=root.DraftEngine.generate(config,'noise-neighbor',view.read());assert.match(out.reply,/測試生活聲響/);assert.equal(out.record,root.NOISE_TEXTS.templates.committeeRecord);});
test('3.2餐飲及異味仍維持原UI設定',async()=>{const {config}=await setup();for(const t of config.templates.filter(t=>t.categoryId==='air'))assert.equal(t.choiceStyle,undefined);});
test('3.2單選卡完成量測、產稿、複製與重測動作仍為一般按鈕',async()=>{const e=await loaded(),doc=documentStub(),app=doc.createElement('main');doc.getElementById=()=>app;e.context.document=doc;e.root.confirm=()=>true;e.root.TemplateLoader.load=async()=>e.config;let copied='';e.context.navigator={clipboard:{writeText:async text=>{copied=text;}}};e.run('src/field-renderer.js');e.run('src/sentence-app.js');await new Promise(r=>setImmediate(r));const get=id=>nodes(app).find(n=>n.id===id),action=t=>nodes(app).find(n=>n.tagName==='BUTTON'&&n.textContent===t);action('噪音').dispatch('click');action('噪音案件').dispatch('click');for(const [id,value]of Object.entries({...base,a9Value_leq:'40',a9WindSpeed:'5'})){const field=get(id);if(field.role==='radiogroup')field.options.find(o=>o.value===value).dispatch('click');else{field.value=value;field.dispatch('change');}}assert.equal(action('填入兩份草稿').role,undefined);action('填入兩份草稿').dispatch('click');assert.ok(get('record').value);action('複製文字').dispatch('click');await Promise.resolve();assert.equal(copied,get('record').value);});
