(function(root){
'use strict';
const PROVENANCE='PP-IA-41-7F3C9A21';
const CFG=()=>root.AIR_V1_CONFIG||{};
const clone=v=>JSON.parse(JSON.stringify(v));
const uid=(prefix='id')=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const nowLocal=()=>{const d=new Date();const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;};
const blankFixed=()=>({
  basic:{inspectionDateTime:nowLocal(),serial:'',controlNo:'',name:'',location:'',itemType:'',industryCode:'',dioxin:'unknown',pollutants:[]},
  sources:[],observations:[],siteObjects:[],
  controls:{presence:'unreviewed',types:[],operation:'unreviewed',collection:'unreviewed',malfunctionReport:'unreviewed',description:''},
  emission:{mode:'unreviewed',pipeDescription:'',emitting:'unreviewed',visibleFlow:'unreviewed',afterControl:'unreviewed',abnormal:'unreviewed',fugitiveDescription:''},
  permitBasic:{status:'unreviewed',types:[],number:'',documents:'unreviewed',deepReview:false},permits:[],
  responsible:{duty:'unreviewed',actual:'unreviewed',form:'',grade:''},notes:''
});
const blankConstruction=()=>({
  basic:{inspectionDateTime:nowLocal(),listed:'unknown',listingNo:'',name:'',publicProject:'unknown',externalGrade:'unknown',legalGrade:'unknown',stage:'unknown',address:'',type:'',permitNo:''},
  work:{phase:'',items:[],other:''},pollutionObservations:[],articleChecks:{},management:{},coating:{enabled:false,paintLiters:'',waterPaintLiters:'',solventPercent:'',solventType:'',notes:''},improvements:[],advice:'',notes:''
});
const blankBurning=()=>({
  basic:{inspectionDateTime:nowLocal(),location:'',placeType:'unknown',burningState:'unknown',purpose:'unknown',purposeSource:'unknown',purposeNote:'',scale:'unknown',area:'',amount:'unknown'},
  materials:[],materialDescription:'',evidence:[],evidenceDescription:'',persons:[],observations:[],disposalLink:{enabled:false,batchRef:'',note:''},disposition:[],notes:''
});
const fresh=()=>({schema:'air-v1',schemaVersion:1,version:'5.1.0',provenance:PROVENANCE,activeMode:'',fixed:blankFixed(),construction:blankConstruction(),burning:blankBurning()});
const isObj=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
function deepMerge(base,input){
  if(Array.isArray(base))return Array.isArray(input)?clone(input):clone(base);
  if(isObj(base)){const out=clone(base);if(isObj(input))for(const [k,v] of Object.entries(input))out[k]=(k in base)?deepMerge(base[k],v):clone(v);return out;}
  return input===undefined||input===null?base:input;
}
function pathValue(obj,path){let cur=obj;for(const key of path){if(!isObj(cur)||!(key in cur))return undefined;cur=cur[key];}return cur;}
function assertArrayAt(input,path,label){const v=pathValue(input,path);if(v!==undefined&&!Array.isArray(v))throw new Error(`空氣污染案件格式無效：${label} 必須是陣列。`);}
function mapObjects(arr,label,make){return (arr||[]).map((item,i)=>{if(!isObj(item))throw new Error(`空氣污染案件格式無效：${label} 第 ${i+1} 筆不是物件。`);return deepMerge(make(),item);});}
function ensureUniqueIds(arr,label){const seen=new Set();for(const item of arr||[]){if(!item.id)throw new Error(`空氣污染案件格式無效：${label} 缺少識別碼。`);if(seen.has(item.id))throw new Error(`空氣污染案件格式無效：${label} 有重複識別碼 ${item.id}。`);seen.add(item.id);}return seen;}
const sourceRecord=()=>({id:uid('src'),name:'',location:'',type:'尚待確認',taxId:'',owner:'',contact:'',phone:'',otherId:'',note:''});
const siteObjectRecord=()=>({id:uid('obj'),type:'製程／作業',name:'',code:'',location:'',status:'unknown',links:[],note:''});
const permitRecord=()=>({id:uid('permit'),type:'操作許可',number:'',purpose:'',objectIds:[],checks:{process:'unreviewed',equipment:'unreviewed',control:'unreviewed',stack:'unreviewed',material:'unreviewed',condition:'unreviewed'},details:{},note:''});
const sourceLinkRecord=()=>({id:uid('rel'),sourceId:'',status:'疑似／待查證',reason:'',observation:'',verification:'',methods:[],operation:'unknown',operationDetail:'',changeBefore:'',changeAfter:'',pollutionChange:'unreviewed',note:''});
const improvementRecord=()=>({id:uid('imp'),time:nowLocal(),measures:[],measureNote:'',links:[],afterObservationId:'',afterObservationNote:'',note:''});
const burningPersonRecord=()=>({id:uid('person'),name:'',identity:'',relation:'不明',admit:'unknown',status:'疑似／待查證',methods:[],note:''});
function normalizeState(input){
  if(!isObj(input))throw new Error('空氣污染案件狀態格式無效。');
  for(const [path,label] of [
    [['fixed','sources'],'固定污染源／來源對象'],[['fixed','observations'],'固定污染源／現場觀察'],[['fixed','siteObjects'],'固定污染源／現場物件'],[['fixed','permits'],'固定污染源／許可'],
    [['construction','pollutionObservations'],'營建工程／現場觀察'],[['construction','improvements'],'營建工程／改善複查'],
    [['burning','materials'],'露天燃燒／燃燒物'],[['burning','evidence'],'露天燃燒／燃燒跡證'],[['burning','persons'],'露天燃燒／行為人'],[['burning','observations'],'露天燃燒／現場觀察'],[['burning','disposition'],'露天燃燒／現場處置']
  ])assertArrayAt(input,path,label);
  const out=fresh();out.fixed=deepMerge(blankFixed(),input.fixed);out.construction=deepMerge(blankConstruction(),input.construction);out.burning=deepMerge(blankBurning(),input.burning);
  out.fixed.sources=mapObjects(out.fixed.sources,'來源對象',sourceRecord);
  out.fixed.observations=mapObjects(out.fixed.observations,'固定污染源現場觀察',newObservation).map(o=>{if(!Array.isArray(o.links))throw new Error('空氣污染案件格式無效：現場觀察來源關聯必須是陣列。');o.links=mapObjects(o.links,'來源關聯',sourceLinkRecord);return o;});
  out.fixed.siteObjects=mapObjects(out.fixed.siteObjects,'現場物件',siteObjectRecord);
  out.fixed.permits=mapObjects(out.fixed.permits,'許可證查核',permitRecord).map(x=>{if(!Array.isArray(x.objectIds))throw new Error('空氣污染案件格式無效：許可證現場物件關聯必須是陣列。');return x;});
  out.construction.pollutionObservations=mapObjects(out.construction.pollutionObservations,'營建現場觀察',constructionObs);
  out.construction.improvements=mapObjects(out.construction.improvements,'改善／複查',improvementRecord).map(x=>{if(!Array.isArray(x.links))throw new Error('空氣污染案件格式無效：改善／缺失關聯必須是陣列。');if(!x.afterObservationNote&&typeof x.afterObservation==='string')x.afterObservationNote=x.afterObservation;return x;});
  if(!isObj(out.construction.articleChecks))throw new Error('空氣污染案件格式無效：營建條文查核必須是物件。');
  for(const [article,raw] of Object.entries(out.construction.articleChecks)){
    if(!isObj(raw))throw new Error(`空氣污染案件格式無效：營建第 ${article} 條查核不是物件。`);
    const x=deepMerge({status:'unreviewed',selectedDefects:[],defectFacts:{},alt:{used:'unknown',approval:'unreviewed',content:'',match:'unreviewed',note:''},note:''},raw);
    if(!Array.isArray(x.selectedDefects)||!isObj(x.defectFacts))throw new Error(`空氣污染案件格式無效：營建第 ${article} 條缺失資料格式錯誤。`);
    for(const [defectId,factRaw] of Object.entries(x.defectFacts)){
      if(!isObj(factRaw))throw new Error(`空氣污染案件格式無效：第 ${article} 條缺失 ${defectId} 的事實資料錯誤。`);
      const fact=deepMerge({fact:'',refs:[],relationNotes:''},factRaw);if(!Array.isArray(fact.refs))throw new Error(`空氣污染案件格式無效：第 ${article} 條缺失 ${defectId} 的觀察關聯必須是陣列。`);fact.refs=mapObjects(fact.refs,`第 ${article} 條缺失觀察關聯`,()=>({observationId:'',relation:'支持'}));x.defectFacts[defectId]=fact;
    }
    out.construction.articleChecks[article]=x;
  }
  out.burning.persons=mapObjects(out.burning.persons,'露天燃燒行為人',burningPersonRecord);
  out.burning.observations=mapObjects(out.burning.observations,'露天燃燒現場觀察',burnObs);
  if(Array.isArray(out.burning.materials))out.burning.materials=[...new Set(out.burning.materials.map(x=>x==='紙類'?'一般紙類':x))];
  const sourceIds=ensureUniqueIds(out.fixed.sources,'來源對象');const fixedObsIds=ensureUniqueIds(out.fixed.observations,'固定污染源現場觀察');const objectIds=ensureUniqueIds(out.fixed.siteObjects,'現場物件');ensureUniqueIds(out.fixed.permits,'許可證查核');
  for(const o of out.fixed.observations)for(const link of o.links||[]){if(!link.sourceId||!sourceIds.has(link.sourceId))throw new Error(`空氣污染案件關聯錯誤：現場觀察 ${o.id} 連到不存在的來源 ${link.sourceId||'(空白)'}。`);}
  for(const permit of out.fixed.permits)for(const id of permit.objectIds||[]){if(!objectIds.has(id))throw new Error(`空氣污染案件關聯錯誤：許可 ${permit.id} 連到不存在的現場物件 ${id}。`);}
  const constructionObsIds=ensureUniqueIds(out.construction.pollutionObservations,'營建現場觀察');ensureUniqueIds(out.construction.improvements,'改善／複查');ensureUniqueIds(out.burning.persons,'露天燃燒行為人');ensureUniqueIds(out.burning.observations,'露天燃燒現場觀察');
  for(const [article,x] of Object.entries(out.construction.articleChecks))for(const [defectId,fact] of Object.entries(x.defectFacts||{}))for(const ref of fact.refs||[]){if(!ref.observationId||!constructionObsIds.has(ref.observationId))throw new Error(`空氣污染案件關聯錯誤：第 ${article} 條缺失 ${defectId} 連到不存在的現場觀察 ${ref.observationId||'(空白)'}。`);}
  const configuredDefects=new Set();for(const a of CFG().construction?.articleChecks||[])for(const d of a.items||[])configuredDefects.add(`${a.article}:${d.id}`);
  for(const imp of out.construction.improvements){for(const link of imp.links||[]){if(!isObj(link)||!link.key)throw new Error(`空氣污染案件格式無效：改善／複查 ${imp.id} 的缺失關聯不完整。`);if(configuredDefects.size&&!configuredDefects.has(link.key))throw new Error(`空氣污染案件關聯錯誤：改善／複查 ${imp.id} 連到未知缺失 ${link.key}。`);}if(imp.afterObservationId&&!constructionObsIds.has(imp.afterObservationId))throw new Error(`空氣污染案件關聯錯誤：改善／複查 ${imp.id} 連到不存在的改善後現場觀察 ${imp.afterObservationId}。`);}
  out.activeMode=String(input.activeMode||'');out.version='5.1.0';out.provenance=PROVENANCE;out.schema='air-v1';out.schemaVersion=1;return out;
}
let state=fresh();let host=null;let mode='';
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined&&text!==null)n.textContent=text;if(cls)n.className=cls;return n;}
const AIR_HELP=Object.freeze({
  '稽查日期時間':'記錄本次到場或查核時間；可用「更新為現在」帶入，必要時再修正。',
  '管制編號（如有）':'僅在已知主管機關列管資料中的正式管制編號時填寫；不確定可留空，不要把系統流水號當成管制編號。',
  '稽查對象／場所':'填寫本次查核的公私場所、工廠、工地或其他對象名稱；名稱尚未確認可先留空。',
  '位置／地址':'記錄實際查核位置或地址；來源尚未確認時可先記現場位置。',
  '固定污染源／製程項目別':'依列管、許可或現場可確認資料記錄主要固定污染源或製程項目；不確定時留空，後續再核對。',
  '行業代碼／類別':'依列管資料或可確認的行業、製程分類填寫；不要只憑現場外觀自行推定。',
  '是否涉及戴奧辛污染':'依製程、設備、原物料、燃料或列管／許可資料確認；資料不足選「尚待確認」。',
  '本次現場實際觀察污染類別（可複選）':'只勾選本次實際觀察到或已有資料支持的污染類別；沒有觀察到不代表不存在。',
  '來源所在方向':'記錄從觀察位置判斷的疑似來源方位；無法判斷可留空。',
  '污染物／氣味移動方向':'依現場煙流、氣味、粉塵或氣流實際移動方向記錄；不確定時不要推定。',
  '與疑似來源方向是否一致':'比較污染移動方向與疑似來源位置是否相符；資料不足選「尚待確認」。',
  '與疑似來源氣味是否相似':'只有在可合理比較時記錄相似程度；無法比較選「尚待確認」。',
  '是否有防制設備':'依現場設備、管線或許可資料確認；未查到不等於沒有。',
  '當下運轉狀態':'記錄到場時設備或製程實際狀態；無法確認可選「本次未查／尚待確認」。',
  '污染物收集狀況':'記錄污染物是否有被集氣、收集或導入防制設備；依現場可見管線及設備狀況確認。',
  '排放方式':'記錄經排放管道、逸散或兩者皆有；尚未查清可保留未確認。',
  '當下是否有排放':'只記錄到場當下是否觀察到排放；沒有看到不代表平時沒有排放。',
  '是否可見煙流／氣流':'依現場目視結果記錄；目視不到時不要反推沒有污染物。',
  '是否經防制設備後排放':'依實際管線與設備流程確認；不確定時保留未確認。',
  '是否發現異常排放':'記錄本次是否有可描述的異常現象；如有應在後續欄位補充具體事實。',
  '許可證狀態':'依主管機關資料或現場文件確認許可狀態；無法核對時選「本次未查」。',
  '許可證資料是否取得':'表示本次是否已取得可供核對的許可內容，不代表許可有效與否。',
  '是否需要進一步核對許可內容':'現場設備、製程、排放或操作情形與許可可能有關時，可進一步建立許可查核。',
  '營建工程是否列管':'依列管資料或可確認的工程規模與類型核對；不確定時選「尚待確認」。',
  '營建工程列管編號':'僅填主管機關列管資料中的正式工程列管編號；未知時留空。',
  '管理辦法工程分級':'依適用管理辦法及工程資料確認，不確定時不要自行推定。',
  '工程階段':'記錄到場時實際施工階段，用於理解當下可能的污染作業。',
  '目前作業內容':'只勾選到場時正在進行或已有事實支持的作業。',
  '到場狀態':'記錄到場時燃燒是否仍持續、僅剩餘燼／灰燼或其他狀態。',
  '場所類型':'依燃燒發生地點的實際用途或環境填寫；不確定可選「尚待確認」。',
  '燃燒用途／目的':'依現場陳述、跡證或其他資料記錄；不要僅由燃燒物種類自動推定用途。',
  '燃燒物大類（可複選）':'只勾選現場可辨識或已有資料支持的燃燒物；不確定可在描述欄補充。',
  '燃燒跡證（可複選）':'記錄灰燼、焦痕、餘燼、煙味等實際可見或可感知跡證。',
  '是否承認燃燒':'記錄當事人陳述，不等同系統認定其為違規行為人。',
  '現場處置（可複選）':'記錄本次實際採取的處置或改善行為，不自動代表案件已完成或違規成立。'
});
function helpFor(label){
  if(!label)return '';
  if(AIR_HELP[label])return AIR_HELP[label];
  if(/備註|補充|說明|描述/.test(label))return '補充本次實際觀察、詢問或文件可支持的內容；不知道的事項不要自行補寫。';
  if(/日期|時間/.test(label))return '依本次實際查核或觀察時間填寫；無法確認時可留空。';
  if(/地址|位置|地號|方向/.test(label))return '依現場位置、圖資或可確認資料記錄；不確定時可先留空或註明待確認。';
  if(/編號|字號|代碼/.test(label))return '依正式列管、許可或文件資料填寫；無法確認時留空，不自行編造。';
  if(/可複選/.test(label))return '只選擇已有現場事實或資料支持的項目；沒有勾選不代表該情形一定不存在。';
  if(/是否|狀態|結果|情形|運轉|排放/.test(label))return '依現場觀察、詢問或文件確認；資料不足時選「尚待確認／本次未查」，未知不等於否定。';
  return '依本次現場可確認的事實填寫；無法確認時可留空或保留「尚待確認／本次未查」，不要自行推定。';
}
function appendHelp(container,label){const text=helpFor(label);if(text)container.append(el('small',text,'air-field-help'));}
function btn(text,fn,secondary=false){const b=el('button',text,secondary?'air-secondary':'');b.type='button';b.addEventListener('click',fn);return b;}
function section(title,description){const s=el('section','', 'air-section');s.append(el('h3',title));if(description)s.append(el('p',description,'air-muted'));return s;}
function grid(cols=2){return el('div','',cols===3?'air-grid three':'air-grid');}
function field(labelText,value,onChange,type='text',opts={}){const l=el('label','', 'air-field');l.append(el('span',labelText));appendHelp(l,labelText);const i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.value=value??'';if(opts.placeholder)i.placeholder=opts.placeholder;if(opts.step)i.step=opts.step;if(opts.min!==undefined)i.min=opts.min;i.addEventListener('input',()=>onChange(i.value));l.append(i);return l;}
function selectField(labelText,value,options,onChange){const l=el('label','', 'air-field');l.append(el('span',labelText));appendHelp(l,labelText);const s=el('select');for(const [v,t] of options){const o=el('option',t);o.value=v;if(v===value)o.selected=true;s.append(o);}s.addEventListener('change',()=>onChange(s.value));l.append(s);return l;}
function checkGroup(title,values,options,onChange){const wrap=el('div');if(title){wrap.append(el('strong',title));appendHelp(wrap,title);}const list=el('div','', 'air-checks');const current=new Set(values||[]);for(const option of options){const label=el('label','', 'air-check');const input=el('input');input.type='checkbox';input.checked=current.has(option);input.addEventListener('change',()=>{input.checked?current.add(option):current.delete(option);onChange([...current]);});label.append(input,el('span',option));list.append(label);}wrap.append(list);return wrap;}
function yesNoUnknown(labelText,value,onChange,includeUnreviewed=true){const opts=[['unknown','尚待確認'],['yes','是'],['no','否']];if(includeUnreviewed)opts.push(['unreviewed','本次未查']);return selectField(labelText,value||'unknown',opts,onChange);}
function removeById(arr,id){const idx=arr.findIndex(x=>x.id===id);if(idx>=0)arr.splice(idx,1);}
function updateNow(target,key='inspectionDateTime'){target[key]=nowLocal();render();}
function scrollToTop(){window.scrollTo?.({top:0,behavior:'smooth'});}
function hasData(){const f=state.fixed,c=state.construction,b=state.burning;const constructionChecks=Object.values(c.articleChecks||{}).some(x=>x&&(x.status!=='unreviewed'||(x.selectedDefects||[]).length||x.note||x.alt?.content||x.alt?.used==='yes'));const fixedBasic=!!(f.basic.name||f.basic.location||f.basic.controlNo||f.basic.serial||f.basic.itemType||f.basic.industryCode||f.basic.pollutants.length||f.basic.dioxin!=='unknown'||f.controls.presence!=='unreviewed'||f.emission.mode!=='unreviewed'||f.permitBasic.status!=='unreviewed'||f.responsible.duty!=='unreviewed'||f.notes);const constructionBasic=!!(c.basic.name||c.basic.address||c.basic.listingNo||c.basic.listed!=='unknown'||c.basic.publicProject!=='unknown'||c.basic.externalGrade!=='unknown'||c.basic.legalGrade!=='unknown'||c.basic.stage!=='unknown'||c.basic.type||c.work.items.length||c.work.phase||c.work.other||c.advice||c.notes);const burningBasic=!!(b.basic.location||b.basic.placeType!=='unknown'||b.basic.burningState!=='unknown'||b.basic.purpose!=='unknown'||b.basic.scale!=='unknown'||b.basic.area||b.basic.amount!=='unknown'||b.materials.length||b.evidence.length||b.disposition.length||b.disposalLink.enabled||b.notes);return !!(fixedBasic||f.sources.length||f.observations.length||f.siteObjects.length||f.permits.length||constructionBasic||constructionChecks||c.pollutionObservations.length||c.improvements.length||burningBasic||b.persons.length||b.observations.length);}
function mount(target,nextMode){host=target;mode=nextMode||state.activeMode||'';state.activeMode=mode;render();}
function render(){if(!host)return;host.replaceChildren();const rootEl=el('div','', 'air-v1');const hero=el('section','', 'air-hero');const title=mode==='air-fixed-source'?'固定污染源／一般空污':mode==='air-construction'?'營建工程':mode==='air-open-burning'?'露天燃燒':'空氣污染';hero.append(el('h2',title),el('p','先記現場事實，再由空氣污染法規研判整理可能法規方向、相反事實與待確認要件；系統不自動認定違法。','air-muted'));rootEl.append(hero);if(mode==='air-fixed-source')renderFixed(rootEl);else if(mode==='air-construction')renderConstruction(rootEl);else if(mode==='air-open-burning')renderBurning(rootEl);else rootEl.append(el('p','尚未選擇空氣污染流程。'));const sticky=el('div','', 'air-sticky');sticky.append(btn('法規研判',()=>root.AirRuleUI?.open?.({mode,state:clone(state)}),true),btn('整理目前內容',()=>showSummary(),true),btn('回到最上面',scrollToTop,true));rootEl.append(sticky);host.append(rootEl);}
function summaryText(){if(mode==='air-fixed-source'){const f=state.fixed;return [`【固定污染源／一般空污】`,`稽查時間：${f.basic.inspectionDateTime||'未填'}`,`對象：${f.basic.name||'未填'} ${f.basic.location||''}`,`管制編號：${f.basic.controlNo||'未填'}`,`污染類別：${f.basic.pollutants.join('、')||'未填'}`,`來源對象：${f.sources.length} 筆`,`現場觀察紀錄：${f.observations.length} 筆`,`現場物件：${f.siteObjects.length} 筆`,`許可證深入查核：${f.permits.length} 張`,`防制設備：${labelMap(f.controls.presence)}`,`排放方式：${labelMap(f.emission.mode)}`].join('\n');}
if(mode==='air-construction'){const c=state.construction;return [`【營建工程】`,`稽查時間：${c.basic.inspectionDateTime||'未填'}`,`工程：${c.basic.name||'未填'}`,`地址／地號：${c.basic.address||'未填'}`,`施工狀況：${c.basic.stage||'未填'}`,`目前作業：${c.work.items.join('、')||'未填'}`,`污染現場觀察：${c.pollutionObservations.length} 筆`,`管理辦法缺失總點數：${constructionTotal()} 點`,`改善／複查：${c.improvements.length} 筆`].join('\n');}
const b=state.burning;return [`【露天燃燒】`,`稽查時間：${b.basic.inspectionDateTime||'未填'}`,`位置：${b.basic.location||'未填'}`,`燃燒狀態：${b.basic.burningState}`,`燃燒物：${b.materials.join('、')||'未填'}`,`燃燒跡證：${b.evidence.join('、')||'未填'}`,`疑似／確認行為人：${b.persons.length} 筆`,`現場觀察紀錄：${b.observations.length} 筆`,`廢棄物連結：${b.disposalLink.enabled?'已標記':'未標記'}`].join('\n');}
function showSummary(){const existing=host.querySelector('.air-summary');existing?.remove();const s=section('目前內容摘要','此摘要僅整理已輸入事實，不是正式稽查紀錄，也不代表違規成立。');s.classList.add('air-summary');const pre=el('div',summaryText(),'air-summary-pre');s.append(pre);host.querySelector('.air-v1')?.insertBefore(s,host.querySelector('.air-sticky'));s.scrollIntoView({behavior:'smooth',block:'start'});}
function labelMap(v){return ({yes:'是',no:'否',unknown:'尚待確認',unreviewed:'本次未查',present:'有設備',none:'無設備',pipe:'經排放管道',fugitive:'未經排放管道逸散',both:'兩者皆有',normal:'正常運轉',stopped:'未運轉',fault:'故障'})[v]||v||'未填';}

function renderFixed(rootEl){const f=state.fixed;
  const basic=section('基本紀錄','以現場輔助為主；身分資料可填可不填，不完整不阻止後續查核。');const g=grid(3);g.append(field('稽查日期時間',f.basic.inspectionDateTime,v=>f.basic.inspectionDateTime=v,'datetime-local'),field('管制編號（如有）',f.basic.controlNo,v=>f.basic.controlNo=v),field('稽查對象／場所',f.basic.name,v=>f.basic.name=v),field('位置／地址',f.basic.location,v=>f.basic.location=v),field('固定污染源／製程項目別',f.basic.itemType,v=>f.basic.itemType=v),field('行業代碼／類別',f.basic.industryCode,v=>f.basic.industryCode=v));basic.append(g);const nowRow=el('div','', 'air-row-actions');nowRow.append(btn('更新為現在',()=>updateNow(f.basic),true));basic.append(nowRow,yesNoUnknown('是否涉及戴奧辛污染',f.basic.dioxin,v=>{f.basic.dioxin=v;}),checkGroup('本次現場實際觀察污染類別（可複選）',f.basic.pollutants,CFG().pollutants||[],v=>{f.basic.pollutants=v;render();}));rootEl.append(basic);
  renderSources(rootEl,f);renderFixedObservations(rootEl,f);renderSiteObjects(rootEl,f);renderControls(rootEl,f);renderEmission(rootEl,f);renderPermit(rootEl,f);renderResponsible(rootEl,f);
  const note=section('其他現場事實');note.append(field('備註',f.notes,v=>f.notes=v,'textarea'));rootEl.append(note);
}
function renderSources(rootEl,f){const s=section('來源對象','同一來源只建立一次；不同現場觀察紀錄再各自建立獨立關聯。');s.append(btn('＋新增來源對象',()=>{f.sources.push(sourceRecord());render();}));if(!f.sources.length)s.append(el('div','尚未建立來源對象。','air-empty'));for(const src of f.sources){const c=el('div','', 'air-card');const h=el('div','', 'air-card-head');h.append(el('h4',src.name||'未命名來源'),btn('刪除',()=>{if(confirm('刪除此來源？相關觀察關聯也會一併移除。')){removeById(f.sources,src.id);for(const o of f.observations)o.links=(o.links||[]).filter(x=>x.sourceId!==src.id);render();}},true));c.append(h);const g=grid(3);g.append(field('名稱／簡稱',src.name,v=>{src.name=v;}),field('地址／位置',src.location,v=>src.location=v),selectField('對象類型',src.type,(CFG().sourceTypes||[]).map(x=>[x,x]),v=>src.type=v),field('統一編號',src.taxId,v=>src.taxId=v),field('負責人／代表人',src.owner,v=>src.owner=v),field('聯絡人',src.contact,v=>src.contact=v),field('聯絡電話',src.phone,v=>src.phone=v),field('其他識別資料',src.otherId,v=>src.otherId=v));c.append(g,field('備註',src.note,v=>src.note=v,'textarea'));s.append(c);}rootEl.append(s);}
function newObservation(){return {id:uid('obs'),time:nowLocal(),location:'',pollutants:[],occurrence:'unknown',windObserved:'unreviewed',sourceDirection:'',movementDirection:'',windMatch:'unknown',odor:{description:'',strength:'',pattern:'',similarity:'unknown',eNose:''},detectors:{VOC:'',SO2:'',NH3:'',H2S:''},blackSmoke:{location:'',mode:'unknown',pattern:'',visualTest:'no',result:''},particle:{location:'',activity:'',mode:'unknown',pattern:'',visible:'unknown'},note:'',links:[]};}
function renderFixedObservations(rootEl,f){const s=section('現場觀察紀錄','同一案件可建立多筆；時間與位置各自保存。每筆觀察可連結 0～多個疑似來源。');s.append(btn('＋新增現場觀察',()=>{f.observations.push(newObservation());render();}));if(!f.observations.length)s.append(el('div','尚無現場觀察紀錄。','air-empty'));for(const [idx,o] of f.observations.entries()){const c=el('div','', 'air-card');const h=el('div','', 'air-card-head');h.append(el('h4',`現場觀察 ${idx+1}`),btn('刪除',()=>{removeById(f.observations,o.id);render();},true));c.append(h);const g=grid(3);g.append(field('觀察時間',o.time,v=>o.time=v,'datetime-local'),field('觀察位置',o.location,v=>o.location=v),selectField('發生狀態',o.occurrence,[['unknown','無法確認'],['continuous','持續'],['intermittent','間歇'],['brief','短暫出現'],['none','未發現']],v=>o.occurrence=v));c.append(g,checkGroup('本筆實際觀察污染類別',o.pollutants,CFG().pollutants||[],v=>{o.pollutants=v;render();}));const wind=grid(3);wind.append(selectField('風向／氣流',o.windObserved,[['unreviewed','本次未記'],['yes','有觀察'],['unknown','無法確認']],v=>o.windObserved=v),field('來源所在方向',o.sourceDirection,v=>o.sourceDirection=v),field('污染物／氣味移動方向',o.movementDirection,v=>o.movementDirection=v),selectField('與疑似來源方向是否一致',o.windMatch,[['unknown','無法確認'],['yes','一致'],['no','不一致']],v=>o.windMatch=v));c.append(wind);
    if(o.pollutants.includes('異味污染物（含惡臭）')){const d=el('details');d.open=true;d.append(el('summary','異味專用欄位'));const body=el('div','', 'air-details-body');const gg=grid(3);gg.append(field('氣味描述',o.odor.description,v=>o.odor.description=v),selectField('氣味強弱',o.odor.strength,[['','未填'],['mild','輕微'],['clear','明顯'],['strong','強烈'],['unknown','無法描述']],v=>o.odor.strength=v),selectField('發生狀態',o.odor.pattern,[['','未填'],['continuous','持續'],['intermittent','間歇'],['brief','短暫']],v=>o.odor.pattern=v),selectField('與疑似來源氣味是否相似',o.odor.similarity,[['unknown','無法確認'],['yes','相似'],['no','不相似']],v=>o.odor.similarity=v),field('電子鼻數值',o.odor.eNose,v=>o.odor.eNose=v,'number',{step:'any'}));body.append(gg);d.append(body);c.append(d);}
    const det=el('details');det.append(el('summary','現場偵測儀數值（VOC／SO₂／NH₃／H₂S）'));const dg=grid(4);dg.append(field('VOC',o.detectors.VOC,v=>o.detectors.VOC=v,'number',{step:'any'}),field('SO₂',o.detectors.SO2,v=>o.detectors.SO2=v,'number',{step:'any'}),field('NH₃',o.detectors.NH3,v=>o.detectors.NH3=v,'number',{step:'any'}),field('H₂S',o.detectors.H2S,v=>o.detectors.H2S=v,'number',{step:'any'}));det.append(el('div','數值僅作現場輔助事實，不直接代表法定超標。','air-law-note'),dg);c.append(det);
    if(o.pollutants.includes('黑煙')){const d=el('details');d.append(el('summary','黑煙專用欄位'));const body=el('div','', 'air-details-body');body.append(field('排放位置／來源設備',o.blackSmoke.location,v=>o.blackSmoke.location=v),selectField('排放方式',o.blackSmoke.mode,[['unknown','無法確認'],['pipe','排放管道'],['fugitive','逸散']],v=>o.blackSmoke.mode=v),field('發生狀態',o.blackSmoke.pattern,v=>o.blackSmoke.pattern=v),selectField('是否進行目測判煙',o.blackSmoke.visualTest,[['no','否'],['yes','是']],v=>o.blackSmoke.visualTest=v),field('目測判煙結果（自由填寫）',o.blackSmoke.result,v=>o.blackSmoke.result=v));d.append(body);c.append(d);}
    if(o.pollutants.includes('粒狀污染物')){const d=el('details');d.append(el('summary','粒狀污染物專用欄位'));const body=el('div','', 'air-details-body');body.append(field('逸散／排放位置',o.particle.location,v=>o.particle.location=v),field('產生作業簡述',o.particle.activity,v=>o.particle.activity=v),selectField('排放方式',o.particle.mode,[['unknown','無法確認'],['pipe','排放管道'],['fugitive','未經管道逸散'],['both','兩者皆有']],v=>o.particle.mode=v),field('發生狀態',o.particle.pattern,v=>o.particle.pattern=v),yesNoUnknown('是否可明顯目視',o.particle.visible,v=>o.particle.visible=v,false));d.append(body);c.append(d);}
    c.append(field('本筆備註',o.note,v=>o.note=v,'textarea'));renderSourceLinks(c,o,f);s.append(c);}rootEl.append(s);}
function renderSourceLinks(card,o,f){const wrap=el('div','', 'air-card air-source-link');wrap.append(el('h4','疑似來源關聯'));if(f.sources.length){const add=el('div','', 'air-inline');const sel=el('select');sel.append(el('option','選擇來源對象'));for(const src of f.sources){const op=el('option',src.name||src.location||src.id);op.value=src.id;sel.append(op);}add.append(sel,btn('＋建立關聯',()=>{if(!sel.value)return;if((o.links||[]).some(x=>x.sourceId===sel.value))return alert('此觀察已連結該來源。');o.links=o.links||[];{const rel=sourceLinkRecord();rel.sourceId=sel.value;o.links.push(rel);};render();},true));wrap.append(add);}else wrap.append(el('p','請先建立來源對象。','air-muted'));
for(const link of o.links||[]){const src=f.sources.find(x=>x.id===link.sourceId);if(!src)continue;const d=el('details');d.open=true;d.append(el('summary',`${src.name||src.location||'來源'}｜${link.status}`));const body=el('div','', 'air-details-body');body.append(selectField('關聯狀態',link.status,(CFG().relationStatuses||[]).map(x=>[x,x]),v=>link.status=v),field('為何懷疑',link.reason,v=>link.reason=v,'textarea'),field('當下觀察',link.observation,v=>link.observation=v,'textarea'),field('查證方式補充',link.verification,v=>link.verification=v,'textarea'),checkGroup('查證方式／佐證來源',link.methods,CFG().evidenceMethods||[],v=>link.methods=v),selectField('疑似來源當下運轉狀態',link.operation,[['unknown','無法確認'],['running','正在運轉'],['partial','部分運轉'],['stopped','未運轉'],['transition','啟動／停機中'],['unreviewed','本次未查']],v=>link.operation=v),field('哪項作業／設備正在運作',link.operationDetail,v=>link.operationDetail=v),field('來源狀態改變前',link.changeBefore,v=>link.changeBefore=v),field('來源狀態改變後',link.changeAfter,v=>link.changeAfter=v),selectField('來源改變後污染現象',link.pollutionChange,[['unreviewed','本次未觀察'],['increase','明顯增加'],['decrease','明顯降低'],['gone','消失'],['same','無明顯改變'],['unknown','無法確認']],v=>link.pollutionChange=v),field('關聯備註',link.note,v=>link.note=v,'textarea'));body.append(btn('移除此關聯',()=>{removeById(o.links,link.id);render();},true));d.append(body);wrap.append(d);}card.append(wrap);}
function renderSiteObjects(rootEl,f){const s=section('輕量現場物件','用於許可核對引用；不要求建立完整製程圖。');s.append(btn('＋新增現場物件',()=>{f.siteObjects.push(siteObjectRecord());render();}));for(const obj of f.siteObjects){const c=el('div','', 'air-card');const g=grid(3);g.append(selectField('類型',obj.type,[['製程／作業','製程／作業'],['主要設備','主要設備'],['防制設備','防制設備'],['排放口','排放口']],v=>obj.type=v),field('名稱',obj.name,v=>obj.name=v),field('編號／位置',obj.code||obj.location,v=>{obj.code=v;obj.location=v;}),selectField('運轉／排放狀態',obj.status,[['unknown','無法確認'],['running','運轉／排放中'],['stopped','未運轉／未排放'],['partial','部分運轉']],v=>obj.status=v));c.append(g,field('備註',obj.note,v=>obj.note=v),btn('刪除',()=>{removeById(f.siteObjects,obj.id);for(const p of f.permits)p.objectIds=(p.objectIds||[]).filter(id=>id!==obj.id);render();},true));s.append(c);}if(!f.siteObjects.length)s.append(el('div','尚未建立現場物件。','air-empty'));rootEl.append(s);}
function renderControls(rootEl,f){const s=section('防制設備','記現場看得到的狀態；不在此直接判斷許可是否相符。');const g=grid(3);g.append(selectField('是否有防制設備',f.controls.presence,[['unreviewed','本次未查'],['none','無設備'],['present','有設備'],['unknown','無法確認']],v=>{f.controls.presence=v;render();}),selectField('當下運轉狀態',f.controls.operation,[['unreviewed','本次未查'],['normal','正常運轉'],['stopped','未運轉'],['fault','故障'],['unknown','無法確認']],v=>{f.controls.operation=v;render();}),selectField('污染物收集狀況',f.controls.collection,[['unreviewed','本次未查'],['effective','有明顯收集並進入設備'],['ineffective','有設備但疑似未有效收集'],['bypass','明顯逸散／旁通'],['unknown','無法確認']],v=>f.controls.collection=v));s.append(g);if(f.controls.presence==='present')s.append(checkGroup('設備類型',f.controls.types,CFG().controlTypes||[],v=>f.controls.types=v));if(f.controls.operation==='fault')s.append(selectField('故障是否已報備',f.controls.malfunctionReport,[['unreviewed','本次未查'],['yes','已報備'],['no','未報備'],['unknown','無法確認']],v=>f.controls.malfunctionReport=v));s.append(field('防制設備簡述／異常情形',f.controls.description,v=>f.controls.description=v,'textarea'));rootEl.append(s);}
function renderEmission(rootEl,f){const s=section('排放管道／逸散狀態','先記客觀排放方式；「是否依規定」留給許可與法規層。');s.append(selectField('排放方式',f.emission.mode,[['unreviewed','本次未查'],['pipe','經排放管道'],['fugitive','未經排放管道逸散'],['both','兩者都有'],['unknown','無法確認']],v=>{f.emission.mode=v;render();}));if(['pipe','both'].includes(f.emission.mode)){const g=grid(3);g.append(field('排放管道位置／簡述',f.emission.pipeDescription,v=>f.emission.pipeDescription=v),yesNoUnknown('當下是否有排放',f.emission.emitting,v=>f.emission.emitting=v),yesNoUnknown('是否可見煙流／氣流',f.emission.visibleFlow,v=>f.emission.visibleFlow=v),yesNoUnknown('是否經防制設備後排放',f.emission.afterControl,v=>f.emission.afterControl=v),yesNoUnknown('是否發現異常排放',f.emission.abnormal,v=>f.emission.abnormal=v));s.append(g);}if(['fugitive','both'].includes(f.emission.mode))s.append(field('逸散位置／來源／作業',f.emission.fugitiveDescription,v=>f.emission.fugitiveDescription=v,'textarea'));rootEl.append(s);}
function renderPermit(rootEl,f){const s=section('許可證基本查核','一般陳情可停在基本確認；有需要時才進入逐項比對。');s.append(selectField('許可證狀態',f.permitBasic.status,[['unreviewed','本次未查'],['not-required','無須申請'],['missing','應申請但未取得'],['obtained','已取得'],['unknown','是否應申請尚待確認']],v=>{f.permitBasic.status=v;render();}));if(f.permitBasic.status==='obtained'){s.append(checkGroup('許可種類',f.permitBasic.types,CFG().permitTypes||[],v=>f.permitBasic.types=v));const g=grid(3);g.append(field('許可證字號（選填）',f.permitBasic.number,v=>f.permitBasic.number=v),yesNoUnknown('許可證資料是否取得',f.permitBasic.documents,v=>f.permitBasic.documents=v),selectField('是否需要進一步核對許可內容',f.permitBasic.deepReview?'yes':'no',[['no','否'],['yes','是']],v=>{f.permitBasic.deepReview=v==='yes';render();}));s.append(g);}if(f.permitBasic.deepReview){s.append(btn('＋新增一張許可證查核',()=>{f.permits.push(permitRecord());render();}));for(const p of f.permits){const c=el('div','', 'air-card');const h=el('div','', 'air-card-head');h.append(el('h4',p.number||'未命名許可證'),btn('刪除',()=>{removeById(f.permits,p.id);render();},true));c.append(h);const g=grid(3);g.append(selectField('許可種類',p.type,(CFG().permitTypes||[]).map(x=>[x,x]),v=>p.type=v),field('許可證字號',p.number,v=>p.number=v),field('對應製程／用途',p.purpose,v=>p.purpose=v));c.append(g);if(f.siteObjects.length)c.append(checkGroup('連結現場物件（選填）',p.objectIds,f.siteObjects.map(x=>x.id),ids=>p.objectIds=ids));const labels={process:'製程',equipment:'主要設備',control:'防制設備',stack:'排放管道',material:'原物料／燃料',condition:'操作條件'};for(const [key,label] of Object.entries(labels)){const d=el('details');d.append(el('summary',`${label}｜${permitCheckLabel(p.checks[key])}`));const body=el('div','', 'air-details-body');body.append(selectField(`${label}核對`,p.checks[key],[['unreviewed','本次未查'],['match','相符'],['different','發現差異'],['unknown','無法確認']],v=>{p.checks[key]=v;render();}));if(p.checks[key]==='different'){p.details[key]=p.details[key]||{permit:'',actual:'',difference:'',evidence:''};const x=p.details[key];body.append(field('許可內容摘要',x.permit,v=>x.permit=v,'textarea'),field('現場實際狀況',x.actual,v=>x.actual=v,'textarea'),field('差異說明',x.difference,v=>x.difference=v,'textarea'),field('查證依據／備註',x.evidence,v=>x.evidence=v,'textarea'));}d.append(body);c.append(d);}c.append(field('本張許可備註',p.note,v=>p.note=v,'textarea'));s.append(c);}}rootEl.append(s);}
function permitCheckLabel(v){return ({unreviewed:'本次未查',match:'相符',different:'發現差異',unknown:'無法確認'})[v]||v;}
function renderResponsible(rootEl,f){const s=section('專責人員／專責單位','維持輕量查核；姓名、證號等深入管理資料暫不放入。');s.append(selectField('依法設置義務',f.responsible.duty,[['unreviewed','本次未查'],['not-required','不須設置'],['required','應設置'],['unknown','是否應設置尚待確認']],v=>{f.responsible.duty=v;render();}));if(f.responsible.duty==='required'){const g=grid(3);g.append(selectField('實際設置狀況',f.responsible.actual,[['unreviewed','本次未查'],['yes','已設置'],['no','未設置'],['unknown','無法確認']],v=>{f.responsible.actual=v;render();}));if(f.responsible.actual==='yes'){g.append(selectField('設置型態',f.responsible.form,[['','未填'],['unit','專責單位'],['person','專責人員']],v=>f.responsible.form=v),selectField('級別',f.responsible.grade,[['','未填'],['A','甲級'],['B','乙級']],v=>f.responsible.grade=v));}s.append(g);}rootEl.append(s);}

function renderConstruction(rootEl){const c=state.construction;const basic=section('工程基本資料','工程分級同時保留外部系統原始級別與管理辦法第一／第二級，避免混用。');const g=grid(3);g.append(field('稽查日期時間',c.basic.inspectionDateTime,v=>c.basic.inspectionDateTime=v,'datetime-local'),yesNoUnknown('營建工程是否列管',c.basic.listed,v=>c.basic.listed=v,false),field('營建工程列管編號',c.basic.listingNo,v=>c.basic.listingNo=v),field('工程名稱',c.basic.name,v=>c.basic.name=v),yesNoUnknown('公共工程',c.basic.publicProject,v=>c.basic.publicProject=v,false),selectField('外部系統原始工程級別',c.basic.externalGrade,[['unknown','尚待確認'],['none','不需分級'],['1','第一級'],['2','第二級'],['3','第三級']],v=>c.basic.externalGrade=v),selectField('管理辦法工程分級',c.basic.legalGrade,[['unknown','尚待確認'],['na','不適用'],['1','第一級'],['2','第二級']],v=>{c.basic.legalGrade=v;render();}),selectField('施工狀況',c.basic.stage,[['unknown','尚待確認'],['尚未施工','尚未施工'],['整地工程','整地工程'],['基礎開挖','基礎開挖'],['佈樁工程','佈樁工程'],['擋土工程','擋土工程'],['地下物主體結構工程','地下物主體結構工程'],['地上物主體結構工程','地上物主體結構工程'],['外部裝修工程','外部裝修工程'],['內部裝修工程','內部裝修工程'],['附屬設施工程','附屬設施工程'],['管線埋設工程','管線埋設工程'],['拆除工程','拆除工程'],['已完工','已完工'],['其他','其他']],v=>{c.basic.stage=v;render();}),field('工地地址或地號',c.basic.address,v=>c.basic.address=v),selectField('工程種類',c.basic.type,[['','未填'],['房屋建築(RC)','房屋建築(RC)'],['房屋建築(SRC)','房屋建築(SRC)'],['房屋建築(拆除)','房屋建築(拆除)'],['道路','道路'],['隧道','隧道'],['管線','管線'],['橋樑','橋樑'],['區域開發(遊樂區)','區域開發(遊樂區)'],['區域開發(工業區)','區域開發(工業區)'],['區域開發(社區)','區域開發(社區)'],['疏濬','疏濬'],['其他營建工程','其他營建工程']],v=>c.basic.type=v),field('建照字號或合約編號',c.basic.permitNo,v=>c.basic.permitNo=v));basic.append(g);const ar=el('div','', 'air-row-actions');ar.append(btn('更新為現在',()=>updateNow(c.basic),true));basic.append(ar);rootEl.append(basic);
renderConstructionWork(rootEl,c);renderConstructionPollution(rootEl,c);renderArticleChecks(rootEl,c);renderConstructionManagement(rootEl,c);renderImprovements(rootEl,c);const s=section('改善建議與其他備註');s.append(field('改善建議事項',c.advice,v=>c.advice=v,'textarea'),field('其他備註',c.notes,v=>c.notes=v,'textarea'));rootEl.append(s);}
function renderConstructionWork(rootEl,c){const s=section('工程概述／目前作業內容','施工狀況是主要階段；目前作業內容可複選，供優先查核項目推薦。');const items=['拆除','搬運','基樁','擋土','開挖','排水','臨時設備','鋼構','混凝土','鋪面','塗裝','粉刷','內部裝修','水電工程','防水','其他'];s.append(selectField('工程階段',c.work.phase,[['','未填'],['前期','前期'],['中期','中期'],['後期','後期']],v=>c.work.phase=v),checkGroup('目前作業內容',c.work.items,items,v=>{c.work.items=v;c.coating.enabled=v.some(x=>['塗裝','粉刷','內部裝修','防水'].includes(x));render();}),field('其他／補充說明',c.work.other,v=>c.work.other=v,'textarea'));if(c.coating.enabled){const d=el('details');d.open=true;d.append(el('summary','塗裝／溶劑相關作業'));const body=el('div','', 'air-details-body');const g=grid(3);g.append(field('油漆塗料用量（L）',c.coating.paintLiters,v=>c.coating.paintLiters=v,'number',{step:'any'}),field('水性塗料用量（L）',c.coating.waterPaintLiters,v=>c.coating.waterPaintLiters=v,'number',{step:'any'}),field('塗料中溶劑含量（%）',c.coating.solventPercent,v=>c.coating.solventPercent=v,'number',{step:'any'}),field('塗料溶劑種類',c.coating.solventType,v=>c.coating.solventType=v),field('備註',c.coating.notes,v=>c.coating.notes=v,'textarea'));body.append(g);d.append(body);s.append(d);}rootEl.append(s);}
function constructionObs(){return {id:uid('cobs'),time:nowLocal(),type:'營建作業造成塵土飛揚',status:'observed',location:'',activity:'',description:'',pattern:'',control:'',articleIds:[],defectRefs:[],note:''};}
function removeConstructionObservation(c,id){removeById(c.pollutionObservations,id);for(const x of Object.values(c.articleChecks||{}))for(const fact of Object.values(x?.defectFacts||{}))fact.refs=(fact.refs||[]).filter(r=>r.observationId!==id);for(const imp of c.improvements||[])if(imp.afterObservationId===id)imp.afterObservationId='';}
function renderConstructionPollution(rootEl,c){const s=section('污染現場觀察紀錄','不是直接勾「有污染行為」；改為保存實際觀察事實。可從這裡建立，也可由 §5～§18 查核項目反向新增。');s.append(btn('＋新增現場觀察',()=>{c.pollutionObservations.push(constructionObs());render();}));const types=['營建作業造成塵土飛揚','粉粒狀物堆置造成塵土飛揚','運送工程材料／廢棄物造成塵土飛揚','其他工事造成塵土飛揚','施工機具排放黑煙','露天燃燒／融化瀝青相關污染','其他'];for(const [idx,o] of c.pollutionObservations.entries()){const card=el('div','', 'air-card');const h=el('div','', 'air-card-head');h.append(el('h4',`現場觀察 ${idx+1}`),btn('刪除',()=>{removeConstructionObservation(c,o.id);render();},true));card.append(h);const g=grid(3);g.append(field('觀察時間',o.time,v=>o.time=v,'datetime-local'),selectField('觀察類型',o.type,types.map(x=>[x,x]),v=>o.type=v),selectField('觀察狀態',o.status,[['observed','有觀察到'],['not-observed','未觀察到'],['unknown','無法確認'],['unreviewed','本次未查']],v=>o.status=v),field('發生位置',o.location,v=>o.location=v),field('實際作業',o.activity,v=>o.activity=v),field('持續情形',o.pattern,v=>o.pattern=v));card.append(g,field('污染現象描述',o.description,v=>o.description=v,'textarea'),field('當下防制措施狀況',o.control,v=>o.control=v,'textarea'),checkGroup('關聯管理辦法條文（可複選）',o.articleIds,(CFG().construction.articleChecks||[]).map(a=>String(a.article)),v=>o.articleIds=v),field('備註',o.note,v=>o.note=v,'textarea'));s.append(card);}if(!c.pollutionObservations.length)s.append(el('div','尚無污染現場觀察。','air-empty'));rootEl.append(s);}
function recommendationSet(c){const set=new Set([5,6,10]);const text=[c.basic.stage,...c.work.items].join(' ');if(/拆除/.test(text))[7,8,10,13,14,16].forEach(x=>set.add(x));if(/開挖|整地|基樁|擋土|搬運/.test(text))[7,8,9,10,13,16].forEach(x=>set.add(x));if(/主體|鋼構|混凝土/.test(text))[8,10,11,12,13,16,17].forEach(x=>set.add(x));if(/裝修|塗裝|粉刷|防水/.test(text))[10,13,16,17].forEach(x=>set.add(x));if(/區域開發|疏濬/.test(c.basic.type))[8,9,10,13,16,18].forEach(x=>set.add(x));return set;}
function checkState(c,a){return c.articleChecks[a.article]||(c.articleChecks[a.article]={status:'unreviewed',selectedDefects:[],defectFacts:{},alt:{used:'unknown',approval:'unreviewed',content:'',match:'unreviewed',note:''},note:''});}
function constructionTotal(){let total=0;for(const a of CFG().construction.articleChecks||[]){const x=state.construction.articleChecks?.[a.article];if(x?.status!=='defect')continue;for(const id of x.selectedDefects||[]){const d=a.items.find(y=>y.id===id);if(d)total+=Number(d.points||0);}}return total;}
function renderArticleChecks(rootEl,c){const s=section('營建工程管理辦法 §5～§18 查核','依施工狀況先標示優先查核項目，但不隱藏其他條文。點數由規則資料顯示與加總；現場觀察本身不會自動改變缺失判斷。');const top=el('div','', 'air-law-note');top.textContent=`${CFG().construction.legalVersion}｜${CFG().construction.pointRuleVersion}`;s.append(top);const rec=recommendationSet(c);const summary=el('div','', 'air-inline');summary.append(el('strong',`目前缺失總點數：${constructionTotal()} 點`),el('span','點數僅為規則彙整；處理方式由法規層另行研判。','air-muted'));s.append(summary);for(const a of CFG().construction.articleChecks||[]){const x=checkState(c,a);const d=el('details','',rec.has(a.article)?'air-recommended':'');d.open=rec.has(a.article)&&['unreviewed','defect'].includes(x.status);const sm=el('summary');sm.append(document.createTextNode(`第${a.article}條｜${a.title} `));if(rec.has(a.article))sm.append(el('span','優先','air-badge'));const subtotal=(x.status==='defect'?(x.selectedDefects||[]).reduce((sum,id)=>sum+(a.items.find(z=>z.id===id)?.points||0),0):0);if(subtotal)sm.append(el('span',`${subtotal}點`,subtotal>=10?'air-badge points10':'air-badge points4'));d.append(sm);const body=el('div','', 'air-details-body');body.append(selectField('整體查核狀態',x.status,[['unreviewed','本次未查'],['no-operation','本項無作業'],['unknown','適用性待確認'],['ok','已查－無缺失'],['defect','已查－發現缺失']],v=>{x.status=v;if(v!=='defect')x.selectedDefects=[];render();}));const row=el('div','', 'air-row-actions');row.append(btn('＋新增相關現場觀察',()=>{const o=constructionObs();o.articleIds=[String(a.article)];c.pollutionObservations.push(o);render();},true));body.append(row);
if(x.status==='defect'){for(const df of a.items){const wrap=el('div','', 'air-defect');const line=el('label','', 'air-check');const input=el('input');input.type='checkbox';input.checked=x.selectedDefects.includes(df.id);input.addEventListener('change',()=>{const set=new Set(x.selectedDefects);input.checked?set.add(df.id):set.delete(df.id);x.selectedDefects=[...set];render();});line.append(input,el('span',df.label),el('span',`${df.points}點`,df.points>=10?'air-badge points10':'air-badge points4'));wrap.append(line);if(x.selectedDefects.includes(df.id)){x.defectFacts[df.id]=x.defectFacts[df.id]||{fact:'',refs:[],relationNotes:''};const fact=x.defectFacts[df.id];wrap.append(field('事實補充',fact.fact,v=>fact.fact=v,'textarea'));const linked=c.pollutionObservations.filter(o=>(o.articleIds||[]).includes(String(a.article)));if(linked.length){const groups=[];for(const o of linked){const ref=fact.refs.find(r=>r.observationId===o.id);const label=el('div','', 'air-inline');const cb=el('input');cb.type='checkbox';cb.checked=!!ref;cb.addEventListener('change',()=>{if(cb.checked)fact.refs.push({observationId:o.id,relation:'支持'});else fact.refs=fact.refs.filter(r=>r.observationId!==o.id);render();});label.append(cb,el('span',`${o.time?.replace('T',' ')||''} ${o.location||o.type}`));if(ref){const sel=el('select');for(const opt of ['支持','相反','待確認','補充']){const op=el('option',opt);op.value=opt;if(opt===ref.relation)op.selected=true;sel.append(op);}sel.addEventListener('change',()=>ref.relation=sel.value);label.append(sel);}groups.push(label);}const refWrap=el('div');refWrap.append(el('strong','關聯現場觀察紀錄'));groups.forEach(n=>refWrap.append(n));wrap.append(refWrap);}wrap.append(field('佐證說明／照片編號（目前不含拍照功能）',fact.relationNotes,v=>fact.relationNotes=v));}body.append(wrap);}body.append(el('div',`本條小計：${subtotal} 點`,'air-score'));}
const alt=el('details');alt.append(el('summary','替代防制措施'));const ab=el('div','', 'air-details-body');ab.append(selectField('是否採用替代防制措施',x.alt.used,[['unknown','無法確認'],['yes','是'],['no','否']],v=>x.alt.used=v),selectField('是否有主管機關同意資料',x.alt.approval,[['unreviewed','本次未查'],['yes','有'],['no','無'],['unknown','尚待確認']],v=>x.alt.approval=v),field('替代措施內容',x.alt.content,v=>x.alt.content=v,'textarea'),selectField('現場是否依同意內容執行',x.alt.match,[['unreviewed','本次未查'],['match','相符'],['different','發現差異'],['unknown','無法確認']],v=>x.alt.match=v),field('替代措施備註',x.alt.note,v=>x.alt.note=v,'textarea'));alt.append(ab);body.append(alt,field('本條整體備註',x.note,v=>x.note=v,'textarea'));d.append(body);s.append(d);}rootEl.append(s);}
function renderConstructionManagement(rootEl,c){const s=section('其他現場管理事項','與 §5～§18 缺失記點分開保存，不納入缺失點數。');const opts=[['done','完成'],['improve','待改善'],['none','無'],['unreviewed','本次未查'],['na','不適用']];for(const key of ['設置告示牌','設置臨時廁所','環保日誌','空污費繳費證明','周圍水體（溝）維護清理']){c.management[key]=c.management[key]||{status:'unreviewed',note:''};const row=el('div','', 'air-card');row.append(selectField(key,c.management[key].status,opts,v=>c.management[key].status=v),field('備註',c.management[key].note,v=>c.management[key].note=v));if(key.includes('水體')){c.management[key].measures=c.management[key].measures||[];row.append(checkGroup('現場措施',c.management[key].measures,['已設置沉砂池','工地周圍排水溝加蓋','工地周圍排水溝定時清理','無防護措施','其他'],v=>c.management[key].measures=v));}s.append(row);}rootEl.append(s);}
function renderImprovements(rootEl,c){const s=section('改善／複查紀錄','原始缺失不覆寫；後續改善另存新紀錄。改善後現場觀察使用真正的現場觀察物件，可選擇既有紀錄或直接新增。');s.append(btn('＋新增改善／複查紀錄',()=>{c.improvements.push(improvementRecord());render();}));const defectOptions=[];for(const a of CFG().construction.articleChecks||[]){const x=c.articleChecks[a.article];if(x?.status==='defect')for(const id of x.selectedDefects||[]){const df=a.items.find(y=>y.id===id);if(df)defectOptions.push({key:`${a.article}:${id}`,label:`第${a.article}條｜${df.label}`});}}
for(const [i,imp] of c.improvements.entries()){const card=el('div','', 'air-card');const h=el('div','', 'air-card-head');h.append(el('h4',`改善／複查 ${i+1}`),btn('刪除',()=>{removeById(c.improvements,imp.id);render();},true));card.append(h,field('時間',imp.time,v=>imp.time=v,'datetime-local'));const rr=el('div','', 'air-row-actions');rr.append(btn('更新為現在',()=>{imp.time=nowLocal();render();},true));card.append(rr,checkGroup('改善措施（可複選）',imp.measures,CFG().construction.improvementMeasures||[],v=>imp.measures=v),field('改善措施補充說明',imp.measureNote,v=>imp.measureNote=v,'textarea'));
if(defectOptions.length){const linkWrap=el('div');linkWrap.append(el('strong','連結缺失與各自改善結果'));for(const opt of defectOptions){let link=imp.links.find(x=>x.key===opt.key);const row=el('div','', 'air-inline');const cb=el('input');cb.type='checkbox';cb.checked=!!link;cb.addEventListener('change',()=>{if(cb.checked)imp.links.push({key:opt.key,result:'pending'});else imp.links=imp.links.filter(x=>x.key!==opt.key);render();});row.append(cb,el('span',opt.label));if(link){const sel=el('select');for(const [v,t] of [['done','已改善'],['partial','部分改善'],['not-done','未改善'],['pending','尚未複查'],['unknown','無法確認']]){const op=el('option',t);op.value=v;if(v===link.result)op.selected=true;sel.append(op);}sel.addEventListener('change',()=>link.result=sel.value);row.append(sel);}linkWrap.append(row);}card.append(linkWrap);}const afterWrap=el('div','', 'air-card');afterWrap.append(el('strong','改善後現場觀察（選填）'));const afterRow=el('div','', 'air-inline');const afterSel=el('select');const none=el('option','未連結現場觀察');none.value='';afterSel.append(none);for(const o of c.pollutionObservations){const op=el('option',`${o.time?.replace('T',' ')||''}｜${o.location||o.type||'現場觀察'}`);op.value=o.id;if(o.id===imp.afterObservationId)op.selected=true;afterSel.append(op);}afterSel.addEventListener('change',()=>{imp.afterObservationId=afterSel.value;render();});afterRow.append(afterSel,btn('＋建立改善後現場觀察',()=>{const o=constructionObs();o.type='其他';o.note=`由改善／複查 ${i+1} 建立之改善後現場觀察`;c.pollutionObservations.push(o);imp.afterObservationId=o.id;render();},true));afterWrap.append(afterRow);if(imp.afterObservationId){const linked=c.pollutionObservations.find(o=>o.id===imp.afterObservationId);if(linked)afterWrap.append(el('div',`已連結：${linked.time?.replace('T',' ')||''}｜${linked.location||linked.type||'現場觀察'}。請在上方「污染現場觀察紀錄」編輯完整事實。`,'air-law-note'));}afterWrap.append(field('改善後觀察補充',imp.afterObservationNote||'',v=>imp.afterObservationNote=v,'textarea'));card.append(afterWrap,field('備註',imp.note,v=>imp.note=v,'textarea'));s.append(card);}if(!c.improvements.length)s.append(el('div','尚無改善／複查紀錄。','air-empty'));rootEl.append(s);}

function renderBurning(rootEl){const b=state.burning;
  const arrival=section('到場狀態','先記到場當下最容易消失的事實；此欄只保存狀態，不控制或隱藏其他區塊。');
  const ag=grid(3);ag.append(field('稽查日期時間',b.basic.inspectionDateTime,v=>b.basic.inspectionDateTime=v,'datetime-local'),field('位置描述／地址',b.basic.location,v=>b.basic.location=v),selectField('到場狀態',b.basic.burningState,[['unknown','無法確認'],['burning','正在燃燒'],['embers','僅剩餘火／餘燼'],['stopped','已停止燃燒，僅有燃燒跡證']],v=>b.basic.burningState=v));arrival.append(ag);const ar=el('div','', 'air-row-actions');ar.append(btn('更新為現在',()=>updateNow(b.basic),true));arrival.append(ar);rootEl.append(arrival);
  renderBurningObservations(rootEl,b);
  const mat=section('燃燒物與燃燒跡證','記錄燒了什麼，以及到場後仍可辨識的灰燼、焦黑、未完全燃燒物等跡證；跡證本身不等於已確認當時污染行為。');mat.append(checkGroup('燃燒物大類（可複選）',b.materials,['植物／農業剩餘物','木材','金紙／紙錢','一般紙類','塑膠','橡膠','一般垃圾','事業廢棄物','建築／裝修廢料','不明物質','其他'],v=>{b.materials=v;render();}),field('實際燃燒物描述',b.materialDescription,v=>b.materialDescription=v,'textarea'),checkGroup('燃燒跡證（可複選）',b.evidence,['灰燼','焦黑痕跡','未完全燃燒物','餘燼／餘火','燃燒容器／焚燒設施','煙味殘留','其他'],v=>b.evidence=v),field('跡證描述',b.evidenceDescription,v=>b.evidenceDescription=v,'textarea'),el('div','發現灰燼、焦黑或其他燃燒跡證，只是現場事實；不代表已確認本次污染行為成立。','air-law-note'));rootEl.append(mat);
  renderBurningPersons(rootEl,b);
  const context=section('場所／用途／規模','這些資料用於補充事件情境；燃燒用途只記現場可確認事實或陳述，不由系統自行推測。');const cg=grid(3);cg.append(selectField('場所類型',b.basic.placeType,[['unknown','無法確認'],['空地','空地'],['農地','農地'],['住宅周邊','住宅周邊'],['工廠／事業場所','工廠／事業場所'],['營建工地','營建工地'],['道路／路旁','道路／路旁'],['河川／堤防周邊','河川／堤防周邊'],['其他','其他']],v=>b.basic.placeType=v),selectField('燃燒用途／目的',b.basic.purpose,[['unknown','不明'],['清理廢棄物','清理廢棄物'],['農業處理','農業處理'],['祭祀','祭祀'],['加熱／烹煮','加熱／烹煮'],['工作用途','工作用途'],['取暖','取暖'],['其他','其他']],v=>b.basic.purpose=v),selectField('用途資訊來源',b.basic.purposeSource,[['unknown','不明'],['statement','當事人陳述'],['observed','現場可確認'],['other','其他']],v=>b.basic.purposeSource=v),selectField('燃燒範圍',b.basic.scale,[['unknown','無法判斷'],['small','小範圍'],['medium','中等'],['large','大範圍']],v=>b.basic.scale=v),field('燃燒面積或尺寸',b.basic.area,v=>b.basic.area=v),selectField('燃燒物量',b.basic.amount,[['unknown','無法判斷'],['small','少量'],['medium','中量'],['large','大量']],v=>b.basic.amount=v));context.append(cg,field('燃燒用途補充',b.basic.purposeNote,v=>b.basic.purposeNote=v,'textarea'));rootEl.append(context);
  const disposition=section('現場處置與廢棄物連結');disposition.append(checkGroup('現場處置（可複選）',b.disposition,['到場時仍燃燒','現場自行停止','經勸導後停止','經要求處理餘火／餘燼','離場時仍持續','無法確認','其他'],v=>b.disposition=v));const w=el('label','', 'air-check');const cb=el('input');cb.type='checkbox';cb.checked=b.disposalLink.enabled;cb.addEventListener('change',()=>{b.disposalLink.enabled=cb.checked;render();});w.append(cb,el('span','疑似涉及廢棄物，標記連結廢棄物查核'));disposition.append(w);if(b.disposalLink.enabled)disposition.append(field('廢棄物物質批次／待查事項參照',b.disposalLink.batchRef,v=>b.disposalLink.batchRef=v),field('跨模組備註',b.disposalLink.note,v=>b.disposalLink.note=v,'textarea'));disposition.append(field('其他備註',b.notes,v=>b.notes=v,'textarea'));rootEl.append(disposition);
}
function renderBurningPersons(rootEl,b){const s=section('疑似／確認行為人','可建立 0～多名；確認其中一人不會自動排除其他人。');s.append(btn('＋新增疑似行為人',()=>{b.persons.push(burningPersonRecord());render();}));for(const p of b.persons){const c=el('div','', 'air-card');const h=el('div','', 'air-card-head');h.append(el('h4',p.name||'未命名行為人'),btn('刪除',()=>{removeById(b.persons,p.id);render();},true));c.append(h);const g=grid(3);g.append(field('姓名／身分',p.name,v=>p.name=v),field('其他識別資料',p.identity,v=>p.identity=v),selectField('與場所關係',p.relation,[['不明','不明'],['地主','地主'],['使用人','使用人'],['管理人','管理人'],['受僱人','受僱人'],['其他','其他']],v=>p.relation=v),yesNoUnknown('是否承認燃燒',p.admit,v=>p.admit=v,false),selectField('行為人關係狀態',p.status,[['疑似／待查證','疑似／待查證'],['已有部分事實支持','已有部分事實支持'],['已確認行為人','已確認行為人'],['已排除','已排除'],['無法確認','無法確認']],v=>p.status=v));c.append(g,checkGroup('查證依據',p.methods,['現場目視','照片','錄影','當事人陳述','他人陳述','地籍／租賃資料','其他'],v=>p.methods=v),field('備註',p.note,v=>p.note=v,'textarea'));s.append(c);}if(!b.persons.length)s.append(el('div','尚未建立疑似行為人。','air-empty'));rootEl.append(s);}
function burnObs(){return {id:uid('bobs'),time:nowLocal(),location:'',burning:'unknown',visibleParticle:'unknown',spread:'unknown',smokeDirection:'',impact:'',pattern:'unknown',particleChange:'unreviewed',smokeChange:'unreviewed',note:''};}
function renderBurningObservations(rootEl,b){const s=section('現場觀察紀錄','可建立多筆時間序列，記錄燃燒停止前後的污染變化。');s.append(btn('＋新增現場觀察',()=>{b.observations.push(burnObs());render();}));for(const [i,o] of b.observations.entries()){const c=el('div','', 'air-card');const h=el('div','', 'air-card-head');h.append(el('h4',`現場觀察 ${i+1}`),btn('刪除',()=>{removeById(b.observations,o.id);render();},true));c.append(h);const g=grid(3);g.append(field('觀察時間',o.time,v=>o.time=v,'datetime-local'),field('觀察位置',o.location,v=>o.location=v),selectField('是否仍在燃燒',o.burning,[['unknown','無法確認'],['yes','是'],['embers','僅餘火星／餘燼'],['no','否']],v=>o.burning=v),yesNoUnknown('是否目視有明顯粒狀污染物',o.visibleParticle,v=>o.visibleParticle=v,false),yesNoUnknown('是否散布於空氣或他人財物',o.spread,v=>o.spread=v,false),field('煙流方向',o.smokeDirection,v=>o.smokeDirection=v),field('影響範圍',o.impact,v=>o.impact=v),selectField('發生狀態',o.pattern,[['unknown','無法確認'],['continuous','持續'],['intermittent','間歇'],['brief','短暫'],['stopped','已停止']],v=>o.pattern=v),selectField('停止／狀態改變後粒狀污染物',o.particleChange,[['unreviewed','本次未觀察'],['increase','明顯增加'],['decrease','明顯降低'],['gone','消失'],['same','無明顯變化'],['unknown','無法確認']],v=>o.particleChange=v),selectField('煙流變化',o.smokeChange,[['unreviewed','本次未觀察'],['continuous','持續'],['decrease','降低'],['gone','消失'],['unknown','無法確認']],v=>o.smokeChange=v));c.append(g,field('備註',o.note,v=>o.note=v,'textarea'));s.append(c);}if(!b.observations.length)s.append(el('div','尚無現場觀察紀錄。','air-empty'));rootEl.append(s);}

root.AirV1UI={mount,reset(){state=fresh();if(host)render();},snapshot(){return clone(state);},restore(input){state=normalizeState(input);if(host)render();},validateState:normalizeState,hasData};
})(window);
